-- ============================================================
-- JLPT Complete Syllabus — Seed Data (generated)
-- ============================================================

INSERT INTO levels (code, title, description, estimated_hours, sort_order) VALUES
('N5', 'JLPT N5 — Beginner', 'Foundational Japanese: particles, basic conjugation, ~800 vocabulary, 100 kanji.', 150, 1),
('N4', 'JLPT N4 — Upper Beginner', 'Plain form, potential/volitional/conditional, ~1500 vocabulary, 300 kanji.', 180, 2),
('N3', 'JLPT N3 — Intermediate', 'Nuanced grammar, keigo introduction, ~3750 vocabulary, 650 kanji.', 220, 3),
('N2', 'JLPT N2 — Upper Intermediate / Business', 'Full keigo, formal written grammar, ~6000 vocabulary, 1000 kanji.', 280, 4),
('N1', 'JLPT N1 — Advanced', 'Literary/archaic grammar, academic vocabulary, ~10000+ words, 2000+ kanji.', 350, 5);

INSERT INTO modules (level_id, title, sort_order) VALUES
(1, 'Foundations — Nouns, Particles, Basic Sentences', 1),
(1, 'Verbs — ます-form & Basic Actions', 2),
(1, 'Adjectives & Descriptions', 3),
(1, 'て-form & Requests', 4),
(1, 'Past Tense & Question Words', 5),
(1, 'Kanji & Reading Basics', 6),
(2, 'Plain Form & Casual Speech', 1),
(2, 'Potential, Volitional & Ability', 2),
(2, 'Conditionals (たら/ば/と/なら)', 3),
(2, 'Giving & Receiving, Passive (intro)', 4),
(2, 'Obligation, Permission & Prohibition', 5),
(2, 'N4 Kanji & Reading', 6),
(3, 'Nuanced Conjunctions & Reasoning', 1),
(3, 'Keigo Introduction', 2),
(3, 'Speculation & Conditionals', 3),
(3, 'Causative & Causative-Passive', 4),
(3, 'N3 Kanji & Reading Comprehension', 5),
(4, 'Formal Written Grammar Patterns', 1),
(4, 'Advanced Keigo & Business Japanese', 2),
(4, 'Nuanced Modality & Emphasis', 3),
(4, 'N2 Kanji & Long-form Reading', 4),
(5, 'Literary & Archaic Grammar Patterns', 1),
(5, 'Rhetorical & Emphatic Patterns', 2),
(5, 'Academic & Abstract Vocabulary', 3),
(5, 'N1 Kanji, Idioms & Native Fluency', 4);

INSERT INTO grammar_points (level_id, pattern, meaning, example_jp, example_romaji, example_en) VALUES
(1, '〜は〜です', 'N1 is N2', 'わたしは がくせいです。', 'Watashi wa gakusei desu.', 'I am a student.'),
(1, '〜じゃありません', 'N is not (casual negative)', 'これは ほんじゃありません。', 'Kore wa hon ja arimasen.', 'This is not a book.'),
(1, '〜も', 'also/too', 'わたしも がくせいです。', 'Watashi mo gakusei desu.', 'I am also a student.'),
(1, '〜の〜', 'possessive/modifying particle', 'これは わたしの ほんです。', 'Kore wa watashi no hon desu.', 'This is my book.'),
(1, 'これ/それ/あれ/どれ', 'this/that/that-over-there/which', 'これは わたしの かばんです。', 'Kore wa watashi no kaban desu.', 'This is my bag.'),
(1, 'ここ/そこ/あそこ/どこ', 'here/there/over-there/where', 'トイレは あそこです。', 'Toire wa asoko desu.', 'The restroom is over there.'),
(1, '〜に あります/います', 'exists at (place)', '本は つくえの うえに あります。', 'Hon wa tsukue no ue ni arimasu.', 'The book is on the desk.'),
(1, '〜から〜まで', 'from...to...', '9時から5時まで はたらきます。', 'Kuji kara goji made hatarakimasu.', 'I work from 9 to 5.'),
(1, 'Vます/ません', 'polite present aff/neg', 'まいあさ コーヒーを のみます。', 'Maiasa koohii o nomimasu.', 'I drink coffee every morning.'),
(1, 'Vました/ませんでした', 'polite past aff/neg', 'きのう えいがを みました。', 'Kinou eiga o mimashita.', 'I watched a movie yesterday.'),
(1, '〜を', 'direct object marker', 'パンを たべます。', 'Pan o tabemasu.', 'I eat bread.'),
(1, '〜に いきます/きます/かえります', 'movement toward destination', 'がっこうに いきます。', 'Gakkou ni ikimasu.', 'I go to school.'),
(1, '〜で (means)', 'by/with (method)', 'バスで がっこうへ いきます。', 'Basu de gakkou e ikimasu.', 'I go to school by bus.'),
(1, '〜と (companion)', 'with (a person)', 'ともだちと えいがを みます。', 'Tomodachi to eiga o mimasu.', 'I watch a movie with a friend.'),
(1, '〜へ', 'direction particle', 'うちへ かえります。', 'Uchi e kaerimasu.', 'I go home.'),
(1, '〜が ほしいです', 'want (a thing)', 'あたらしい くるまが ほしいです。', 'Atarashii kuruma ga hoshii desu.', 'I want a new car.'),
(1, 'Vたいです', 'want to (verb)', 'にほんに いきたいです。', 'Nihon ni ikitai desu.', 'I want to go to Japan.'),
(1, '〜が すきです/きらいです', 'like/dislike', 'すしが すきです。', 'Sushi ga suki desu.', 'I like sushi.'),
(1, 'い-adjective + Noun', 'attributive い-adj', 'おおきい いえ', 'Ookii ie', 'a big house'),
(1, 'な-adjective + Noun', 'attributive な-adj', 'きれいな はな', 'Kirei na hana', 'a beautiful flower'),
(1, 'い-adj negation くない', 'not (い-adj)', 'たかくない', 'takakunai', 'not expensive'),
(1, 'な-adj negation じゃありません', 'not (な-adj)', 'しずかじゃありません', 'shizuka ja arimasen', 'not quiet'),
(1, '〜より', 'comparison — than', 'にほんは アメリカより ちいさいです。', 'Nihon wa amerika yori chiisai desu.', 'Japan is smaller than America.'),
(1, '〜の なかで〜いちばん', 'superlative — most, of all', 'くだものの なかで りんごが いちばん すきです。', 'Kudamono no naka de ringo ga ichiban suki desu.', 'Of all fruits, I like apples the most.'),
(1, 'て-form (request)', 'please do', 'まどを あけてください。', 'Mado o akete kudasai.', 'Please open the window.'),
(1, '〜ています', 'ongoing action/state', 'いま べんきょうしています。', 'Ima benkyoushiteimasu.', 'I am studying now.'),
(1, 'V1て、V2', 'sequential actions', 'あさごはんを たべて、がっこうへ いきます。', 'Asagohan o tabete, gakkou e ikimasu.', 'I eat breakfast, then go to school.'),
(1, 'い-adj past かった', 'past tense い-adj', 'たかかった', 'takakatta', 'was expensive'),
(1, 'な-adj past でした', 'past tense な-adj', 'しずかでした', 'shizuka deshita', 'was quiet'),
(1, '疑問詞 だれ/なに/いつ/どこ/どうして/いくら', 'question words', 'これは いくらですか。', 'Kore wa ikura desu ka.', 'How much is this?'),
(2, '辞書形', 'dictionary form (plain present)', 'たべる', 'taberu', 'to eat'),
(2, 'ない形', 'plain negative', 'たべない', 'tabenai', 'not eat'),
(2, 'た形', 'plain past', 'たべた', 'tabeta', 'ate'),
(2, 'なかった形', 'plain past negative', 'たべなかった', 'tabenakatta', 'did not eat'),
(2, '〜と思います', 'I think that...', 'あした あめが ふると おもいます。', 'Ashita ame ga furu to omoimasu.', 'I think it will rain tomorrow.'),
(2, '〜と言いました', 'said that...', '先生は あしたテストがあると言いました。', 'Sensei wa ashita tesuto ga aru to iimashita.', 'The teacher said there''s a test tomorrow.'),
(2, '可能形 (える/られる)', 'potential form — can do', 'かける／たべられる', 'kakeru / taberareru', 'can write / can eat'),
(2, '〜ができます', 'can do N', 'にほんごが できます。', 'Nihongo ga dekimasu.', 'I can speak Japanese.'),
(2, '意向形 (よう/ましょう)', 'volitional — let''s do', 'いっしょに いこう。', 'Issho ni ikou.', 'Let''s go together.'),
(2, '〜ようと思います', 'I intend to...', 'らいねん にほんに いこうとおもいます。', 'Rainen nihon ni ikou to omoimasu.', 'I intend to go to Japan next year.'),
(2, '〜たら', 'general conditional', 'あめが ふったら、いきません。', 'Ame ga futtara, ikimasen.', 'If it rains, I won''t go.'),
(2, '〜ば', 'hypothetical conditional', 'はやく おきれば、まにあいます。', 'Hayaku okireba, maniaimasu.', 'If you wake up early, you''ll make it.'),
(2, '〜と (natural result)', 'automatic consequence', 'はるに なると、さくらが さきます。', 'Haru ni naru to, sakura ga sakimasu.', 'When spring comes, cherry blossoms bloom.'),
(2, '〜なら', 'conditional on premise', 'にほんに いくなら、パスポートが ひつようです。', 'Nihon ni iku nara, pasupooto ga hitsuyou desu.', 'If you''re going to Japan, you need a passport.'),
(2, 'あげる/もらう/くれる', 'give/receive verbs', '友達が わたしに プレゼントを くれました。', 'Tomodachi ga watashi ni purezento o kuremashita.', 'My friend gave me a present.'),
(2, '受身形', 'passive form', 'わたしは先生にほめられました。', 'Watashi wa sensei ni homeraremashita.', 'I was praised by the teacher.'),
(2, '〜なければなりません', 'must do', 'しゅくだいを しなければなりません。', 'Shukudai o shinakereba narimasen.', 'I must do my homework.'),
(2, '〜てもいいです', 'permission', 'ここで しゃしんを とってもいいです。', 'Koko de shashin o tottemo ii desu.', 'You may take photos here.'),
(2, '〜てはいけません', 'prohibition', 'ここで たばこを すってはいけません。', 'Koko de tabako o suttewa ikemasen.', 'You must not smoke here.'),
(2, '〜そうです (伝聞)', 'hearsay — I heard that', 'あしたは あめが ふるそうです。', 'Ashita wa ame ga furu sou desu.', 'I heard it will rain tomorrow.'),
(2, '〜でしょう', 'probability', 'あしたは はれるでしょう。', 'Ashita wa hareru deshou.', 'It will probably be sunny tomorrow.'),
(2, '〜てみる', 'try doing', 'たべてみます。', 'Tabete mimasu.', 'I''ll try eating it.'),
(2, '〜ておく', 'do in advance / leave as is', 'じゅんびしておきます。', 'Junbi shite okimasu.', 'I''ll prepare in advance.'),
(2, '〜てしまう', 'completion / regret', 'わすれてしまいました。', 'Wasurete shimaimashita.', 'I ended up forgetting.'),
(2, '〜すぎる', 'too much', 'たべすぎました。', 'Tabesugimashita.', 'I ate too much.'),
(2, '〜やすい/にくい', 'easy/hard to do', 'この本は よみやすいです。', 'Kono hon wa yomiyasui desu.', 'This book is easy to read.'),
(3, '〜ため(に)', 'purpose/cause', 'けんこうの ために、まいにち はしります。', 'Kenkou no tame ni, mainichi hashirimasu.', 'I run every day for my health.'),
(3, '〜のに', 'despite/although', 'べんきょうしたのに、テストが できませんでした。', 'Benkyou shita noni, tesuto ga dekimasen deshita.', 'Despite studying, I couldn''t do well on the test.'),
(3, '〜わりに', 'considering/for what it''s worth', 'やすいわりに、おいしいです。', 'Yasui wari ni, oishii desu.', 'It''s cheap, yet tasty.'),
(3, '〜ながら', 'doing two things at once', 'おんがくを ききながら、べんきょうします。', 'Ongaku o kikinagara, benkyoushimasu.', 'I study while listening to music.'),
(3, '〜あいだ(に)', 'while/during the interval of', 'るすの あいだに、でんわが ありました。', 'Rusu no aida ni, denwa ga arimashita.', 'There was a phone call while I was out.'),
(3, '尊敬語 お〜になる', 'respectful form', '先生が おかきになりました。', 'Sensei ga okaki ni narimashita.', 'The teacher wrote (respectful).'),
(3, '謙譲語 お〜する', 'humble form', 'わたしが おつたえします。', 'Watashi ga otsutae shimasu.', 'I will convey it (humble).'),
(3, '特別な尊敬語 いらっしゃる/おっしゃる', 'irregular respectful verbs', '社長は いらっしゃいますか。', 'Shachou wa irasshaimasu ka.', 'Is the president in? (respectful)'),
(3, '特別な謙譲語 まいる/もうす', 'irregular humble verbs', 'わたしが まいります。', 'Watashi ga mairimasu.', 'I will go (humble).'),
(3, '〜はずです', 'should be / expected', '彼は もうすぐ くるはずです。', 'Kare wa mou sugu kuru hazu desu.', 'He should be arriving soon.'),
(3, '〜かもしれません', 'might/may', 'あした あめが ふるかもしれません。', 'Ashita ame ga furu kamoshiremasen.', 'It might rain tomorrow.'),
(3, '〜にちがいない', 'must be (certainty)', 'あの人は 先生に ちがいない。', 'Ano hito wa sensei ni chigainai.', 'That person must be a teacher.'),
(3, '使役形 (せる/させる)', 'causative — make/let do', 'こどもに やさいを たべさせました。', 'Kodomo ni yasai o tabesasemashita.', 'I made the child eat vegetables.'),
(3, '使役受身形', 'causative-passive — forced to do', 'こどものとき、やさいを たべさせられました。', 'Kodomo no toki, yasai o tabesaseraremashita.', 'I was made to eat vegetables as a child.'),
(3, '〜ことになる', 'it has been decided that', 'らいねん てんきんすることになりました。', 'Rainen tenkin suru koto ni narimashita.', 'It''s been decided I''ll transfer next year.'),
(3, '〜ことにする', 'decide to (one''s own choice)', '毎朝 はしることにしました。', 'Maiasa hashiru koto ni shimashita.', 'I''ve decided to run every morning.'),
(3, '〜ば〜ほど', 'the more..., the more...', '勉強すればするほど、わかります。', 'Benkyou sureba suru hodo, wakarimasu.', 'The more I study, the more I understand.'),
(3, '〜おかげで', 'thanks to', '先生の おかげで、合格しました。', 'Sensei no okage de, goukaku shimashita.', 'Thanks to my teacher, I passed.'),
(3, '〜せいで', 'because of (negative)', '雨の せいで、遅刻しました。', 'Ame no sei de, chikoku shimashita.', 'I was late because of the rain.'),
(3, '〜ように', 'so that / in order to', 'わすれないように、メモします。', 'Wasurenai you ni, memo shimasu.', 'I''ll take notes so I don''t forget.'),
(4, '〜にもかかわらず', 'despite/in spite of', 'あめだった にもかかわらず、しあいは おこなわれた。', 'Ame datta nimo kakawarazu, shiai wa okonawareta.', 'Despite the rain, the match was held.'),
(4, '〜ものの', 'although (formal)', 'やくそくした ものの、いけなかった。', 'Yakusoku shita monono, ikenakatta.', 'Although I promised, I couldn''t go.'),
(4, '〜ばかりに', 'just because of (bad result)', 'うそを ついた ばかりに、しんようを うしなった。', 'Uso o tsuita bakari ni, shin''you o ushinatta.', 'Just because he lied, he lost trust.'),
(4, '〜あげく', 'after all that (negative outcome)', 'なやんだ あげく、あきらめた。', 'Nayanda ageku, akirameta.', 'After much agonizing, I gave up.'),
(4, '〜うえで', 'in the process of / on the basis of', 'けいやくする うえで、ちゅういが ひつようです。', 'Keiyaku suru ue de, chuui ga hitsuyou desu.', 'Care is needed in the process of contracting.'),
(4, '〜かぎり', 'as long as / to the extent that', 'わたしの しる かぎり、それは ほんとうです。', 'Watashi no shiru kagiri, sore wa hontou desu.', 'As far as I know, that''s true.'),
(4, '〜わけではない', 'it''s not that... (partial negation)', 'かならずしも きらいなわけではない。', 'Kanarazushimo kirai na wake dewanai.', 'It''s not that I dislike it entirely.'),
(4, '〜どころか', 'far from / let alone', 'やすむどころか、ざんぎょうも した。', 'Yasumu dokoroka, zangyou mo shita.', 'Far from resting, I even worked overtime.'),
(4, '〜させていただきます', 'extra-humble ''allow me to''', 'せつめいさせていただきます。', 'Setsumei sasete itadakimasu.', 'Allow me to explain.'),
(4, '恐れ入りますが', 'cushioning phrase before request', 'おそれいりますが、少々おまちください。', 'Osoreirimasu ga, shoushou omachi kudasai.', 'I''m terribly sorry, but please wait a moment.'),
(4, '〜ないことには', 'unless...(won''t happen)', 'やってみないことには、わからない。', 'Yatte minai koto niwa, wakaranai.', 'Unless you try, you won''t know.'),
(4, '〜てからでないと', 'not until after doing', 'かくにんしてからでないと、すすめられません。', 'Kakunin shite kara denai to, susumeraremasen.', 'We can''t proceed until after confirming.'),
(4, '〜ずにはいられない', 'can''t help but do', 'その本を よむと、なきずにはいられない。', 'Sono hon o yomu to, naki zuniwa irarenai.', 'Reading that book, I can''t help but cry.'),
(4, '〜きり', 'only / ever since', '一度 会ったきり、会っていない。', 'Ichido atta kiri, atteinai.', 'I haven''t seen them since we met once.'),
(4, '〜つつある', 'in the process of (change)', 'じょうきょうは かいぜんしつつある。', 'Joukyou wa kaizen shitsutsu aru.', 'The situation is in the process of improving.'),
(5, '〜べからず', 'classical prohibition — must not', 'ここに ごみを すてるべからず。', 'Koko ni gomi o suteru bekarazu.', 'Do not dump trash here (formal notice).'),
(5, '〜なくして(は)', 'without... (impossible to)', '努力なくして、成功はない。', 'Doryoku nakushite, seikou wa nai.', 'Without effort, there''s no success.'),
(5, '〜をもって', 'by means of / with (formal)', '本日をもって、閉店いたします。', 'Honjitsu o motte, heiten itashimasu.', 'As of today, we are closing (formal).'),
(5, '〜いかんによらず', 'regardless of', '結果のいかんによらず、努力はむだではない。', 'Kekka no ikan ni yorazu, doryoku wa muda dewanai.', 'Regardless of the outcome, the effort isn''t wasted.'),
(5, '〜や否や', 'the moment... (literary)', 'ドアが開くやいなや、彼は飛び出した。', 'Doa ga hiraku ya inaya, kare wa tobidashita.', 'The moment the door opened, he dashed out.'),
(5, '〜そばから', 'no sooner than (repeated)', '習うそばから、忘れてしまう。', 'Narau soba kara, wasurete shimau.', 'I forget as soon as I learn it.'),
(5, '〜なしに', 'without doing (formal)', 'ことわりなしに、使わないでください。', 'Kotowari nashi ni, tsukawanaide kudasai.', 'Please don''t use it without permission.'),
(5, '〜ないまでも', 'even if not... (at least)', '毎日とはいかないまでも、週に一度は運動する。', 'Mainichi towa ikanaimademo, shuu ni ichido wa undou suru.', 'Even if not daily, I exercise at least once a week.'),
(5, '〜きらいがある', 'tends to (unfavorably)', '彼は 悲観的になるきらいがある。', 'Kare wa hikanteki ni naru kirai ga aru.', 'He tends to become pessimistic.'),
(5, '〜にたえない', 'cannot bear to / unworthy of', '見るにたえない ひさんな 光景だった。', 'Miru ni taenai hisan na koukei datta.', 'It was a tragic sight I couldn''t bear to watch.'),
(5, '〜を禁じ得ない', 'cannot help but feel', 'どうじょうを 禁じ得ない。', 'Doujou o kinjienai.', 'I cannot help but feel sympathy.'),
(5, '〜ならでは', 'uniquely characteristic of', 'この味は この店ならではだ。', 'Kono aji wa kono mise naradewa da.', 'This flavor is unique to this shop.'),
(5, '〜んばかりに', 'as if about to (vivid)', '泣かんばかりに 頼んだ。', 'Nakanbakari ni tanonda.', 'He begged as if about to cry.'),
(5, '〜てやまない', 'never ceasing to (formal, emotional)', 'ご成功を 祈ってやみません。', 'Go seikou o inotte yamimasen.', 'I sincerely wish you continued success.'),
(5, '〜極まりない', 'extremely (negative, formal)', '失礼きわまりない 態度だった。', 'Shitsurei kiwamarinai taido datta.', 'It was an extremely rude attitude.');

INSERT INTO vocabulary (level_id, word_jp, reading, romaji, meaning_en, part_of_speech) VALUES
(1, '私', 'わたし', 'watashi', 'I', 'pronoun'),
(1, '学生', 'がくせい', 'gakusei', 'student', 'noun'),
(1, '先生', 'せんせい', 'sensei', 'teacher', 'noun'),
(1, '会社員', 'かいしゃいん', 'kaishain', 'company employee', 'noun'),
(1, '本', 'ほん', 'hon', 'book', 'noun'),
(1, '机', 'つくえ', 'tsukue', 'desk', 'noun'),
(1, '椅子', 'いす', 'isu', 'chair', 'noun'),
(1, '学校', 'がっこう', 'gakkou', 'school', 'noun'),
(1, '先週', 'せんしゅう', 'senshuu', 'last week', 'noun'),
(1, '今日', 'きょう', 'kyou', 'today', 'noun'),
(1, '明日', 'あした', 'ashita', 'tomorrow', 'noun'),
(1, '昨日', 'きのう', 'kinou', 'yesterday', 'noun'),
(1, '食べる', 'たべる', 'taberu', 'to eat', 'verb'),
(1, '飲む', 'のむ', 'nomu', 'to drink', 'verb'),
(1, '行く', 'いく', 'iku', 'to go', 'verb'),
(1, '来る', 'くる', 'kuru', 'to come', 'verb'),
(1, '帰る', 'かえる', 'kaeru', 'to return/go home', 'verb'),
(1, '見る', 'みる', 'miru', 'to see/watch', 'verb'),
(1, '聞く', 'きく', 'kiku', 'to listen/ask', 'verb'),
(1, '読む', 'よむ', 'yomu', 'to read', 'verb'),
(1, '書く', 'かく', 'kaku', 'to write', 'verb'),
(1, '話す', 'はなす', 'hanasu', 'to speak', 'verb'),
(1, '大きい', 'おおきい', 'ookii', 'big', 'i-adj'),
(1, '小さい', 'ちいさい', 'chiisai', 'small', 'i-adj'),
(1, '高い', 'たかい', 'takai', 'expensive/tall', 'i-adj'),
(1, '安い', 'やすい', 'yasui', 'cheap', 'i-adj'),
(1, '新しい', 'あたらしい', 'atarashii', 'new', 'i-adj'),
(1, '古い', 'ふるい', 'furui', 'old', 'i-adj'),
(1, '静か', 'しずか', 'shizuka', 'quiet', 'na-adj'),
(1, 'きれい', 'きれい', 'kirei', 'pretty/clean', 'na-adj'),
(1, '元気', 'げんき', 'genki', 'healthy/energetic', 'na-adj'),
(1, '好き', 'すき', 'suki', 'like', 'na-adj'),
(1, '水', 'みず', 'mizu', 'water', 'noun'),
(1, 'お茶', 'おちゃ', 'ocha', 'tea', 'noun'),
(1, 'パン', 'ぱん', 'pan', 'bread', 'noun'),
(1, '肉', 'にく', 'niku', 'meat', 'noun'),
(1, '魚', 'さかな', 'sakana', 'fish', 'noun'),
(1, '野菜', 'やさい', 'yasai', 'vegetable', 'noun'),
(1, '車', 'くるま', 'kuruma', 'car', 'noun'),
(1, '電車', 'でんしゃ', 'densha', 'train', 'noun'),
(1, 'バス', 'ばす', 'basu', 'bus', 'noun'),
(1, '駅', 'えき', 'eki', 'station', 'noun'),
(1, '家', 'いえ', 'ie', 'house', 'noun'),
(1, '部屋', 'へや', 'heya', 'room', 'noun'),
(1, '窓', 'まど', 'mado', 'window', 'noun'),
(1, 'ドア', 'どあ', 'doa', 'door', 'noun'),
(1, '天気', 'てんき', 'tenki', 'weather', 'noun'),
(1, '雨', 'あめ', 'ame', 'rain', 'noun'),
(1, '雪', 'ゆき', 'yuki', 'snow', 'noun'),
(1, '風', 'かぜ', 'kaze', 'wind', 'noun'),
(1, '友達', 'ともだち', 'tomodachi', 'friend', 'noun'),
(1, '家族', 'かぞく', 'kazoku', 'family', 'noun'),
(2, '使う', 'つかう', 'tsukau', 'to use', 'verb'),
(2, '働く', 'はたらく', 'hataraku', 'to work', 'verb'),
(2, '走る', 'はしる', 'hashiru', 'to run', 'verb'),
(2, '歩く', 'あるく', 'aruku', 'to walk', 'verb'),
(2, '待つ', 'まつ', 'matsu', 'to wait', 'verb'),
(2, '座る', 'すわる', 'suwaru', 'to sit', 'verb'),
(2, '立つ', 'たつ', 'tatsu', 'to stand', 'verb'),
(2, '作る', 'つくる', 'tsukuru', 'to make', 'verb'),
(2, '習う', 'ならう', 'narau', 'to learn', 'verb'),
(2, '教える', 'おしえる', 'oshieru', 'to teach', 'verb'),
(2, '忘れる', 'わすれる', 'wasureru', 'to forget', 'verb'),
(2, '覚える', 'おぼえる', 'oboeru', 'to memorize', 'verb'),
(2, '始まる', 'はじまる', 'hajimaru', 'to begin (intr.)', 'verb'),
(2, '終わる', 'おわる', 'owaru', 'to end', 'verb'),
(2, '開ける', 'あける', 'akeru', 'to open', 'verb'),
(2, '閉める', 'しめる', 'shimeru', 'to close', 'verb'),
(2, '経済', 'けいざい', 'keizai', 'economy', 'noun'),
(2, '会議', 'かいぎ', 'kaigi', 'meeting', 'noun'),
(2, '約束', 'やくそく', 'yakusoku', 'promise', 'noun'),
(2, '準備', 'じゅんび', 'junbi', 'preparation', 'noun'),
(2, '習慣', 'しゅうかん', 'shuukan', 'habit/custom', 'noun'),
(2, '経験', 'けいけん', 'keiken', 'experience', 'noun'),
(2, '危険', 'きけん', 'kiken', 'dangerous', 'na-adj'),
(2, '安全', 'あんぜん', 'anzen', 'safe', 'na-adj'),
(2, '親切', 'しんせつ', 'shinsetsu', 'kind', 'na-adj'),
(2, '便利', 'べんり', 'benri', 'convenient', 'na-adj'),
(2, '不便', 'ふべん', 'fuben', 'inconvenient', 'na-adj'),
(2, '大切', 'たいせつ', 'taisetsu', 'important', 'na-adj'),
(2, '難しい', 'むずかしい', 'muzukashii', 'difficult', 'i-adj'),
(2, '易しい', 'やさしい', 'yasashii', 'easy/kind', 'i-adj'),
(2, '忙しい', 'いそがしい', 'isogashii', 'busy', 'i-adj'),
(2, '楽しい', 'たのしい', 'tanoshii', 'fun', 'i-adj'),
(2, '悲しい', 'かなしい', 'kanashii', 'sad', 'i-adj'),
(2, '嬉しい', 'うれしい', 'ureshii', 'happy', 'i-adj'),
(2, '空港', 'くうこう', 'kuukou', 'airport', 'noun'),
(2, '旅行', 'りょこう', 'ryokou', 'travel', 'noun'),
(2, '荷物', 'にもつ', 'nimotsu', 'luggage', 'noun'),
(2, '切符', 'きっぷ', 'kippu', 'ticket', 'noun'),
(2, '病院', 'びょういん', 'byouin', 'hospital', 'noun'),
(2, '薬', 'くすり', 'kusuri', 'medicine', 'noun'),
(2, '熱', 'ねつ', 'netsu', 'fever', 'noun'),
(2, '風邪', 'かぜ', 'kaze', 'cold (illness)', 'noun'),
(3, '影響', 'えいきょう', 'eikyou', 'influence/impact', 'noun'),
(3, '傾向', 'けいこう', 'keikou', 'tendency', 'noun'),
(3, '対策', 'たいさく', 'taisaku', 'countermeasure', 'noun'),
(3, '課題', 'かだい', 'kadai', 'issue/task', 'noun'),
(3, '環境', 'かんきょう', 'kankyou', 'environment', 'noun'),
(3, '社会', 'しゃかい', 'shakai', 'society', 'noun'),
(3, '政治', 'せいじ', 'seiji', 'politics', 'noun'),
(3, '文化', 'ぶんか', 'bunka', 'culture', 'noun'),
(3, '契約', 'けいやく', 'keiyaku', 'contract', 'noun'),
(3, '報告', 'ほうこく', 'houkoku', 'report', 'noun'),
(3, '説明', 'せつめい', 'setsumei', 'explanation', 'noun'),
(3, '実現', 'じつげん', 'jitsugen', 'realization', 'noun'),
(3, '解決', 'かいけつ', 'kaiketsu', 'solution/resolve', 'noun'),
(3, '向上', 'こうじょう', 'koujou', 'improvement', 'noun'),
(3, '維持', 'いじ', 'iji', 'maintenance', 'noun'),
(3, '改善', 'かいぜん', 'kaizen', 'improvement', 'noun'),
(3, '矛盾', 'むじゅん', 'mujun', 'contradiction', 'noun'),
(3, '信頼', 'しんらい', 'shinrai', 'trust', 'noun'),
(3, '批判', 'ひはん', 'hihan', 'criticism', 'noun'),
(3, '評価', 'ひょうか', 'hyouka', 'evaluation', 'noun'),
(3, '複雑', 'ふくざつ', 'fukuzatsu', 'complex', 'na-adj'),
(3, '単純', 'たんじゅん', 'tanjun', 'simple', 'na-adj'),
(3, '豊か', 'ゆたか', 'yutaka', 'abundant', 'na-adj'),
(3, '深刻', 'しんこく', 'shinkoku', 'serious/grave', 'na-adj'),
(3, '柔軟', 'じゅうなん', 'juunan', 'flexible', 'na-adj'),
(3, '積極的', 'せっきょくてき', 'sekkyokuteki', 'proactive', 'na-adj'),
(3, '消極的', 'しょうきょくてき', 'shoukyokuteki', 'passive', 'na-adj'),
(3, '客観的', 'きゃっかんてき', 'kyakkanteki', 'objective', 'na-adj'),
(4, '概念', 'がいねん', 'gainen', 'concept', 'noun'),
(4, '本質', 'ほんしつ', 'honshitsu', 'essence', 'noun'),
(4, '論理', 'ろんり', 'ronri', 'logic', 'noun'),
(4, '必然性', 'ひつぜんせい', 'hitsuzensei', 'inevitability', 'noun'),
(4, '要素', 'ようそ', 'youso', 'element/factor', 'noun'),
(4, '背景', 'はいけい', 'haikei', 'background', 'noun'),
(4, '視点', 'してん', 'shiten', 'viewpoint', 'noun'),
(4, '観点', 'かんてん', 'kanten', 'perspective', 'noun'),
(4, '前提', 'ぜんてい', 'zentei', 'premise', 'noun'),
(4, '根拠', 'こんきょ', 'konkyo', 'basis/grounds', 'noun'),
(4, '推測', 'すいそく', 'suisoku', 'speculation', 'noun'),
(4, '懸念', 'けねん', 'kenen', 'concern/worry', 'noun'),
(4, '普及', 'ふきゅう', 'fukyuu', 'widespread adoption', 'noun'),
(4, '促進', 'そくしん', 'sokushin', 'promotion (of a process)', 'noun'),
(4, '抑制', 'よくせい', 'yokusei', 'suppression/restraint', 'noun'),
(4, '是正', 'ぜせい', 'zesei', 'correction/rectification', 'noun'),
(4, '顕著', 'けんちょ', 'kencho', 'remarkable/notable', 'na-adj'),
(4, '曖昧', 'あいまい', 'aimai', 'ambiguous', 'na-adj'),
(4, '妥当', 'だとう', 'datou', 'valid/appropriate', 'na-adj'),
(4, '深遠', 'しんえん', 'shin''en', 'profound', 'na-adj'),
(5, '矛盾', 'むじゅん', 'mujun', 'contradiction', 'noun'),
(5, '必然', 'ひつぜん', 'hitsuzen', 'inevitability', 'noun'),
(5, '懐疑', 'かいぎ', 'kaigi', 'skepticism', 'noun'),
(5, '洞察', 'どうさつ', 'dousatsu', 'insight', 'noun'),
(5, '包摂', 'ほうせつ', 'housetsu', 'subsumption/inclusion', 'noun'),
(5, '逸脱', 'いつだつ', 'itsudatsu', 'deviation', 'noun'),
(5, '示唆', 'しさ', 'shisa', 'suggestion/implication', 'noun'),
(5, '弊害', 'へいがい', 'heigai', 'harmful effect', 'noun'),
(5, '是非', 'ぜひ', 'zehi', 'right and wrong / by all means', 'noun'),
(5, '端緒', 'たんしょ', 'tansho', 'beginning/clue', 'noun'),
(5, '普遍的', 'ふへんてき', 'fuhenteki', 'universal', 'na-adj'),
(5, '恣意的', 'しいてき', 'shiiteki', 'arbitrary', 'na-adj'),
(5, '刹那的', 'せつなてき', 'setsunateki', 'momentary/fleeting', 'na-adj'),
(5, '画一的', 'かくいつてき', 'kakuitsuteki', 'uniform/standardized', 'na-adj');
