-- ============================================================
-- JLPT Complete Syllabus — Auto-generated Quiz Question Bank
-- Total questions: 514
-- ============================================================

INSERT INTO quiz_questions (level_id, module_id, source_type, source_id, question_type, question_text, options, correct_index, explanation, difficulty) VALUES
(1, 6, 'vocabulary', 1, 'meaning', 'What does 「私」(わたし) mean?', '["tomorrow", "new", "I", "to speak"]'::jsonb, 2, '私 (わたし/watashi) means ''I''.', 'easy'),
(1, 6, 'vocabulary', 1, 'reading', 'How do you read 「私」?', '["わたし", "ほん", "たかい", "くるま"]'::jsonb, 0, '私 is read ''わたし'' (watashi), meaning ''I''.', 'medium'),
(1, 6, 'vocabulary', 2, 'meaning', 'What does 「学生」(がくせい) mean?', '["desk", "student", "quiet", "old"]'::jsonb, 1, '学生 (がくせい/gakusei) means ''student''.', 'easy'),
(1, 6, 'vocabulary', 2, 'reading', 'How do you read 「学生」?', '["がくせい", "ほん", "せんしゅう", "やさい"]'::jsonb, 0, '学生 is read ''がくせい'' (gakusei), meaning ''student''.', 'medium'),
(1, 6, 'vocabulary', 3, 'meaning', 'What does 「先生」(せんせい) mean?', '["car", "new", "teacher", "vegetable"]'::jsonb, 2, '先生 (せんせい/sensei) means ''teacher''.', 'easy'),
(1, 6, 'vocabulary', 3, 'reading', 'How do you read 「先生」?', '["きょう", "よむ", "さかな", "せんせい"]'::jsonb, 3, '先生 is read ''せんせい'' (sensei), meaning ''teacher''.', 'medium'),
(1, 6, 'vocabulary', 4, 'meaning', 'What does 「会社員」(かいしゃいん) mean?', '["company employee", "fish", "vegetable", "to write"]'::jsonb, 0, '会社員 (かいしゃいん/kaishain) means ''company employee''.', 'easy'),
(1, 6, 'vocabulary', 4, 'reading', 'How do you read 「会社員」?', '["がっこう", "かいしゃいん", "さかな", "たかい"]'::jsonb, 1, '会社員 is read ''かいしゃいん'' (kaishain), meaning ''company employee''.', 'medium'),
(1, 6, 'vocabulary', 5, 'meaning', 'What does 「本」(ほん) mean?', '["bus", "water", "to go", "book"]'::jsonb, 3, '本 (ほん/hon) means ''book''.', 'easy'),
(1, 6, 'vocabulary', 5, 'reading', 'How do you read 「本」?', '["げんき", "ほん", "くるま", "たかい"]'::jsonb, 1, '本 is read ''ほん'' (hon), meaning ''book''.', 'medium'),
(1, 6, 'vocabulary', 6, 'meaning', 'What does 「机」(つくえ) mean?', '["desk", "friend", "to return/go home", "door"]'::jsonb, 0, '机 (つくえ/tsukue) means ''desk''.', 'easy'),
(1, 6, 'vocabulary', 6, 'reading', 'How do you read 「机」?', '["おおきい", "ぱん", "みず", "つくえ"]'::jsonb, 3, '机 is read ''つくえ'' (tsukue), meaning ''desk''.', 'medium'),
(1, 6, 'vocabulary', 7, 'meaning', 'What does 「椅子」(いす) mean?', '["old", "last week", "chair", "tea"]'::jsonb, 2, '椅子 (いす/isu) means ''chair''.', 'easy'),
(1, 6, 'vocabulary', 7, 'reading', 'How do you read 「椅子」?', '["いす", "ふるい", "せんせい", "みず"]'::jsonb, 0, '椅子 is read ''いす'' (isu), meaning ''chair''.', 'medium'),
(1, 6, 'vocabulary', 8, 'meaning', 'What does 「学校」(がっこう) mean?', '["big", "door", "small", "school"]'::jsonb, 3, '学校 (がっこう/gakkou) means ''school''.', 'easy'),
(1, 6, 'vocabulary', 8, 'reading', 'How do you read 「学校」?', '["つくえ", "ほん", "きく", "がっこう"]'::jsonb, 3, '学校 is read ''がっこう'' (gakkou), meaning ''school''.', 'medium'),
(1, 6, 'vocabulary', 9, 'meaning', 'What does 「先週」(せんしゅう) mean?', '["company employee", "rain", "last week", "door"]'::jsonb, 2, '先週 (せんしゅう/senshuu) means ''last week''.', 'easy'),
(1, 6, 'vocabulary', 9, 'reading', 'How do you read 「先週」?', '["せんしゅう", "てんき", "よむ", "やすい"]'::jsonb, 0, '先週 is read ''せんしゅう'' (senshuu), meaning ''last week''.', 'medium'),
(1, 6, 'vocabulary', 10, 'meaning', 'What does 「今日」(きょう) mean?', '["bus", "today", "yesterday", "small"]'::jsonb, 1, '今日 (きょう/kyou) means ''today''.', 'easy'),
(1, 6, 'vocabulary', 10, 'reading', 'How do you read 「今日」?', '["きょう", "いく", "よむ", "ともだち"]'::jsonb, 0, '今日 is read ''きょう'' (kyou), meaning ''today''.', 'medium'),
(1, 6, 'vocabulary', 11, 'meaning', 'What does 「明日」(あした) mean?', '["new", "desk", "tomorrow", "water"]'::jsonb, 2, '明日 (あした/ashita) means ''tomorrow''.', 'easy'),
(1, 6, 'vocabulary', 11, 'reading', 'How do you read 「明日」?', '["さかな", "きく", "せんしゅう", "あした"]'::jsonb, 3, '明日 is read ''あした'' (ashita), meaning ''tomorrow''.', 'medium'),
(1, 6, 'vocabulary', 12, 'meaning', 'What does 「昨日」(きのう) mean?', '["old", "small", "weather", "yesterday"]'::jsonb, 3, '昨日 (きのう/kinou) means ''yesterday''.', 'easy'),
(1, 6, 'vocabulary', 12, 'reading', 'How do you read 「昨日」?', '["きのう", "つくえ", "きょう", "たべる"]'::jsonb, 0, '昨日 is read ''きのう'' (kinou), meaning ''yesterday''.', 'medium'),
(1, 6, 'vocabulary', 13, 'meaning', 'What does 「食べる」(たべる) mean?', '["I", "car", "to eat", "water"]'::jsonb, 2, '食べる (たべる/taberu) means ''to eat''.', 'easy'),
(1, 6, 'vocabulary', 13, 'reading', 'How do you read 「食べる」?', '["わたし", "きょう", "たべる", "ふるい"]'::jsonb, 2, '食べる is read ''たべる'' (taberu), meaning ''to eat''.', 'medium'),
(1, 6, 'vocabulary', 14, 'meaning', 'What does 「飲む」(のむ) mean?', '["to drink", "tea", "door", "last week"]'::jsonb, 0, '飲む (のむ/nomu) means ''to drink''.', 'easy'),
(1, 6, 'vocabulary', 14, 'reading', 'How do you read 「飲む」?', '["いす", "すき", "あたらしい", "のむ"]'::jsonb, 3, '飲む is read ''のむ'' (nomu), meaning ''to drink''.', 'medium'),
(1, 6, 'vocabulary', 15, 'meaning', 'What does 「行く」(いく) mean?', '["pretty/clean", "to go", "book", "to drink"]'::jsonb, 1, '行く (いく/iku) means ''to go''.', 'easy'),
(1, 6, 'vocabulary', 15, 'reading', 'How do you read 「行く」?', '["かいしゃいん", "いく", "いす", "でんしゃ"]'::jsonb, 1, '行く is read ''いく'' (iku), meaning ''to go''.', 'medium'),
(1, 6, 'vocabulary', 16, 'meaning', 'What does 「来る」(くる) mean?', '["chair", "expensive/tall", "to come", "meat"]'::jsonb, 2, '来る (くる/kuru) means ''to come''.', 'easy'),
(1, 6, 'vocabulary', 16, 'reading', 'How do you read 「来る」?', '["ばす", "くる", "やすい", "きょう"]'::jsonb, 1, '来る is read ''くる'' (kuru), meaning ''to come''.', 'medium'),
(1, 6, 'vocabulary', 17, 'meaning', 'What does 「帰る」(かえる) mean?', '["like", "water", "school", "to return/go home"]'::jsonb, 3, '帰る (かえる/kaeru) means ''to return/go home''.', 'easy'),
(1, 6, 'vocabulary', 17, 'reading', 'How do you read 「帰る」?', '["かえる", "つくえ", "きょう", "かく"]'::jsonb, 0, '帰る is read ''かえる'' (kaeru), meaning ''to return/go home''.', 'medium'),
(1, 6, 'vocabulary', 18, 'meaning', 'What does 「見る」(みる) mean?', '["to see/watch", "snow", "like", "to return/go home"]'::jsonb, 0, '見る (みる/miru) means ''to see/watch''.', 'easy'),
(1, 6, 'vocabulary', 18, 'reading', 'How do you read 「見る」?', '["みる", "のむ", "たかい", "ぱん"]'::jsonb, 0, '見る is read ''みる'' (miru), meaning ''to see/watch''.', 'medium'),
(1, 6, 'vocabulary', 19, 'meaning', 'What does 「聞く」(きく) mean?', '["to listen/ask", "bread", "to write", "wind"]'::jsonb, 0, '聞く (きく/kiku) means ''to listen/ask''.', 'easy'),
(1, 6, 'vocabulary', 19, 'reading', 'How do you read 「聞く」?', '["きく", "たかい", "ぱん", "あした"]'::jsonb, 0, '聞く is read ''きく'' (kiku), meaning ''to listen/ask''.', 'medium'),
(1, 6, 'vocabulary', 20, 'meaning', 'What does 「読む」(よむ) mean?', '["bus", "to read", "station", "to go"]'::jsonb, 1, '読む (よむ/yomu) means ''to read''.', 'easy'),
(1, 6, 'vocabulary', 20, 'reading', 'How do you read 「読む」?', '["たべる", "ゆき", "いく", "よむ"]'::jsonb, 3, '読む is read ''よむ'' (yomu), meaning ''to read''.', 'medium'),
(1, 6, 'vocabulary', 21, 'meaning', 'What does 「書く」(かく) mean?', '["to see/watch", "student", "family", "to write"]'::jsonb, 3, '書く (かく/kaku) means ''to write''.', 'easy'),
(1, 6, 'vocabulary', 21, 'reading', 'How do you read 「書く」?', '["どあ", "でんしゃ", "ちいさい", "かく"]'::jsonb, 3, '書く is read ''かく'' (kaku), meaning ''to write''.', 'medium'),
(1, 6, 'vocabulary', 22, 'meaning', 'What does 「話す」(はなす) mean?', '["to go", "desk", "to speak", "expensive/tall"]'::jsonb, 2, '話す (はなす/hanasu) means ''to speak''.', 'easy'),
(1, 6, 'vocabulary', 22, 'reading', 'How do you read 「話す」?', '["おおきい", "たべる", "のむ", "はなす"]'::jsonb, 3, '話す is read ''はなす'' (hanasu), meaning ''to speak''.', 'medium'),
(1, 6, 'vocabulary', 23, 'meaning', 'What does 「大きい」(おおきい) mean?', '["house", "big", "small", "like"]'::jsonb, 1, '大きい (おおきい/ookii) means ''big''.', 'easy'),
(1, 6, 'vocabulary', 23, 'reading', 'How do you read 「大きい」?', '["てんき", "やすい", "おおきい", "かぞく"]'::jsonb, 2, '大きい is read ''おおきい'' (ookii), meaning ''big''.', 'medium'),
(1, 6, 'vocabulary', 24, 'meaning', 'What does 「小さい」(ちいさい) mean?', '["small", "family", "quiet", "station"]'::jsonb, 0, '小さい (ちいさい/chiisai) means ''small''.', 'easy'),
(1, 6, 'vocabulary', 24, 'reading', 'How do you read 「小さい」?', '["あたらしい", "ちいさい", "ゆき", "げんき"]'::jsonb, 1, '小さい is read ''ちいさい'' (chiisai), meaning ''small''.', 'medium'),
(1, 6, 'vocabulary', 25, 'meaning', 'What does 「高い」(たかい) mean?', '["tomorrow", "expensive/tall", "student", "last week"]'::jsonb, 1, '高い (たかい/takai) means ''expensive/tall''.', 'easy'),
(1, 6, 'vocabulary', 25, 'reading', 'How do you read 「高い」?', '["いえ", "きょう", "ばす", "たかい"]'::jsonb, 3, '高い is read ''たかい'' (takai), meaning ''expensive/tall''.', 'medium'),
(1, 6, 'vocabulary', 26, 'meaning', 'What does 「安い」(やすい) mean?', '["fish", "last week", "cheap", "today"]'::jsonb, 2, '安い (やすい/yasui) means ''cheap''.', 'easy'),
(1, 6, 'vocabulary', 26, 'reading', 'How do you read 「安い」?', '["ゆき", "せんしゅう", "ぱん", "やすい"]'::jsonb, 3, '安い is read ''やすい'' (yasui), meaning ''cheap''.', 'medium'),
(1, 6, 'vocabulary', 27, 'meaning', 'What does 「新しい」(あたらしい) mean?', '["to return/go home", "student", "new", "to drink"]'::jsonb, 2, '新しい (あたらしい/atarashii) means ''new''.', 'easy'),
(1, 6, 'vocabulary', 27, 'reading', 'How do you read 「新しい」?', '["かぜ", "くるま", "あたらしい", "かく"]'::jsonb, 2, '新しい is read ''あたらしい'' (atarashii), meaning ''new''.', 'medium'),
(1, 6, 'vocabulary', 28, 'meaning', 'What does 「古い」(ふるい) mean?', '["last week", "old", "company employee", "snow"]'::jsonb, 1, '古い (ふるい/furui) means ''old''.', 'easy'),
(1, 6, 'vocabulary', 28, 'reading', 'How do you read 「古い」?', '["ふるい", "おちゃ", "にく", "せんしゅう"]'::jsonb, 0, '古い is read ''ふるい'' (furui), meaning ''old''.', 'medium'),
(1, 6, 'vocabulary', 29, 'meaning', 'What does 「静か」(しずか) mean?', '["friend", "yesterday", "quiet", "pretty/clean"]'::jsonb, 2, '静か (しずか/shizuka) means ''quiet''.', 'easy'),
(1, 6, 'vocabulary', 29, 'reading', 'How do you read 「静か」?', '["すき", "しずか", "ばす", "きょう"]'::jsonb, 1, '静か is read ''しずか'' (shizuka), meaning ''quiet''.', 'medium'),
(1, 6, 'vocabulary', 30, 'meaning', 'What does 「きれい」(きれい) mean?', '["window", "bread", "to write", "pretty/clean"]'::jsonb, 3, 'きれい (きれい/kirei) means ''pretty/clean''.', 'easy'),
(1, 6, 'vocabulary', 30, 'reading', 'How do you read 「きれい」?', '["みる", "たべる", "きれい", "くる"]'::jsonb, 2, 'きれい is read ''きれい'' (kirei), meaning ''pretty/clean''.', 'medium'),
(1, 6, 'vocabulary', 31, 'meaning', 'What does 「元気」(げんき) mean?', '["healthy/energetic", "wind", "student", "fish"]'::jsonb, 0, '元気 (げんき/genki) means ''healthy/energetic''.', 'easy'),
(1, 6, 'vocabulary', 31, 'reading', 'How do you read 「元気」?', '["ばす", "げんき", "でんしゃ", "おちゃ"]'::jsonb, 1, '元気 is read ''げんき'' (genki), meaning ''healthy/energetic''.', 'medium'),
(1, 6, 'vocabulary', 32, 'meaning', 'What does 「好き」(すき) mean?', '["tea", "quiet", "meat", "like"]'::jsonb, 3, '好き (すき/suki) means ''like''.', 'easy'),
(1, 6, 'vocabulary', 32, 'reading', 'How do you read 「好き」?', '["かえる", "どあ", "すき", "ぱん"]'::jsonb, 2, '好き is read ''すき'' (suki), meaning ''like''.', 'medium'),
(1, 6, 'vocabulary', 33, 'meaning', 'What does 「水」(みず) mean?', '["cheap", "new", "school", "water"]'::jsonb, 3, '水 (みず/mizu) means ''water''.', 'easy'),
(1, 6, 'vocabulary', 33, 'reading', 'How do you read 「水」?', '["ふるい", "くる", "みず", "へや"]'::jsonb, 2, '水 is read ''みず'' (mizu), meaning ''water''.', 'medium'),
(1, 6, 'vocabulary', 34, 'meaning', 'What does 「お茶」(おちゃ) mean?', '["family", "tea", "friend", "school"]'::jsonb, 1, 'お茶 (おちゃ/ocha) means ''tea''.', 'easy'),
(1, 6, 'vocabulary', 34, 'reading', 'How do you read 「お茶」?', '["かえる", "せんしゅう", "きょう", "おちゃ"]'::jsonb, 3, 'お茶 is read ''おちゃ'' (ocha), meaning ''tea''.', 'medium'),
(1, 6, 'vocabulary', 35, 'meaning', 'What does 「パン」(ぱん) mean?', '["tomorrow", "bread", "cheap", "like"]'::jsonb, 1, 'パン (ぱん/pan) means ''bread''.', 'easy'),
(1, 6, 'vocabulary', 35, 'reading', 'How do you read 「パン」?', '["はなす", "やすい", "みず", "ぱん"]'::jsonb, 3, 'パン is read ''ぱん'' (pan), meaning ''bread''.', 'medium'),
(1, 6, 'vocabulary', 36, 'meaning', 'What does 「肉」(にく) mean?', '["meat", "desk", "to write", "rain"]'::jsonb, 0, '肉 (にく/niku) means ''meat''.', 'easy'),
(1, 6, 'vocabulary', 36, 'reading', 'How do you read 「肉」?', '["にく", "しずか", "きれい", "さかな"]'::jsonb, 0, '肉 is read ''にく'' (niku), meaning ''meat''.', 'medium'),
(1, 6, 'vocabulary', 37, 'meaning', 'What does 「魚」(さかな) mean?', '["bus", "to listen/ask", "fish", "tea"]'::jsonb, 2, '魚 (さかな/sakana) means ''fish''.', 'easy'),
(1, 6, 'vocabulary', 37, 'reading', 'How do you read 「魚」?', '["つくえ", "さかな", "いす", "かえる"]'::jsonb, 1, '魚 is read ''さかな'' (sakana), meaning ''fish''.', 'medium'),
(1, 6, 'vocabulary', 38, 'meaning', 'What does 「野菜」(やさい) mean?', '["to see/watch", "wind", "last week", "vegetable"]'::jsonb, 3, '野菜 (やさい/yasai) means ''vegetable''.', 'easy'),
(1, 6, 'vocabulary', 38, 'reading', 'How do you read 「野菜」?', '["やすい", "きょう", "ぱん", "やさい"]'::jsonb, 3, '野菜 is read ''やさい'' (yasai), meaning ''vegetable''.', 'medium'),
(1, 6, 'vocabulary', 39, 'meaning', 'What does 「車」(くるま) mean?', '["company employee", "desk", "car", "to see/watch"]'::jsonb, 2, '車 (くるま/kuruma) means ''car''.', 'easy'),
(1, 6, 'vocabulary', 39, 'reading', 'How do you read 「車」?', '["えき", "くるま", "がくせい", "みる"]'::jsonb, 1, '車 is read ''くるま'' (kuruma), meaning ''car''.', 'medium'),
(1, 6, 'vocabulary', 40, 'meaning', 'What does 「電車」(でんしゃ) mean?', '["train", "to go", "car", "book"]'::jsonb, 0, '電車 (でんしゃ/densha) means ''train''.', 'easy'),
(1, 6, 'vocabulary', 40, 'reading', 'How do you read 「電車」?', '["にく", "わたし", "はなす", "でんしゃ"]'::jsonb, 3, '電車 is read ''でんしゃ'' (densha), meaning ''train''.', 'medium'),
(1, 6, 'vocabulary', 41, 'meaning', 'What does 「バス」(ばす) mean?', '["bus", "weather", "teacher", "tea"]'::jsonb, 0, 'バス (ばす/basu) means ''bus''.', 'easy'),
(1, 6, 'vocabulary', 41, 'reading', 'How do you read 「バス」?', '["かえる", "きのう", "ばす", "かいしゃいん"]'::jsonb, 2, 'バス is read ''ばす'' (basu), meaning ''bus''.', 'medium'),
(1, 6, 'vocabulary', 42, 'meaning', 'What does 「駅」(えき) mean?', '["station", "tea", "wind", "to drink"]'::jsonb, 0, '駅 (えき/eki) means ''station''.', 'easy'),
(1, 6, 'vocabulary', 42, 'reading', 'How do you read 「駅」?', '["おおきい", "えき", "みる", "がくせい"]'::jsonb, 1, '駅 is read ''えき'' (eki), meaning ''station''.', 'medium'),
(1, 6, 'vocabulary', 43, 'meaning', 'What does 「家」(いえ) mean?', '["student", "house", "water", "rain"]'::jsonb, 1, '家 (いえ/ie) means ''house''.', 'easy'),
(1, 6, 'vocabulary', 43, 'reading', 'How do you read 「家」?', '["くる", "しずか", "いす", "いえ"]'::jsonb, 3, '家 is read ''いえ'' (ie), meaning ''house''.', 'medium'),
(1, 6, 'vocabulary', 44, 'meaning', 'What does 「部屋」(へや) mean?', '["cheap", "bread", "room", "water"]'::jsonb, 2, '部屋 (へや/heya) means ''room''.', 'easy'),
(1, 6, 'vocabulary', 44, 'reading', 'How do you read 「部屋」?', '["いく", "たべる", "へや", "はなす"]'::jsonb, 2, '部屋 is read ''へや'' (heya), meaning ''room''.', 'medium'),
(1, 6, 'vocabulary', 45, 'meaning', 'What does 「窓」(まど) mean?', '["window", "last week", "I", "company employee"]'::jsonb, 0, '窓 (まど/mado) means ''window''.', 'easy'),
(1, 6, 'vocabulary', 45, 'reading', 'How do you read 「窓」?', '["まど", "あした", "かいしゃいん", "ふるい"]'::jsonb, 0, '窓 is read ''まど'' (mado), meaning ''window''.', 'medium'),
(1, 6, 'vocabulary', 46, 'meaning', 'What does 「ドア」(どあ) mean?', '["water", "door", "to listen/ask", "house"]'::jsonb, 1, 'ドア (どあ/doa) means ''door''.', 'easy'),
(1, 6, 'vocabulary', 46, 'reading', 'How do you read 「ドア」?', '["せんせい", "きのう", "どあ", "きれい"]'::jsonb, 2, 'ドア is read ''どあ'' (doa), meaning ''door''.', 'medium'),
(1, 6, 'vocabulary', 47, 'meaning', 'What does 「天気」(てんき) mean?', '["I", "to return/go home", "weather", "small"]'::jsonb, 2, '天気 (てんき/tenki) means ''weather''.', 'easy'),
(1, 6, 'vocabulary', 47, 'reading', 'How do you read 「天気」?', '["よむ", "くる", "てんき", "せんせい"]'::jsonb, 2, '天気 is read ''てんき'' (tenki), meaning ''weather''.', 'medium'),
(1, 6, 'vocabulary', 48, 'meaning', 'What does 「雨」(あめ) mean?', '["rain", "expensive/tall", "to speak", "I"]'::jsonb, 0, '雨 (あめ/ame) means ''rain''.', 'easy'),
(1, 6, 'vocabulary', 48, 'reading', 'How do you read 「雨」?', '["あめ", "みず", "たべる", "えき"]'::jsonb, 0, '雨 is read ''あめ'' (ame), meaning ''rain''.', 'medium'),
(1, 6, 'vocabulary', 49, 'meaning', 'What does 「雪」(ゆき) mean?', '["to return/go home", "desk", "today", "snow"]'::jsonb, 3, '雪 (ゆき/yuki) means ''snow''.', 'easy'),
(1, 6, 'vocabulary', 49, 'reading', 'How do you read 「雪」?', '["がくせい", "やすい", "ゆき", "よむ"]'::jsonb, 2, '雪 is read ''ゆき'' (yuki), meaning ''snow''.', 'medium'),
(1, 6, 'vocabulary', 50, 'meaning', 'What does 「風」(かぜ) mean?', '["desk", "wind", "tea", "vegetable"]'::jsonb, 1, '風 (かぜ/kaze) means ''wind''.', 'easy'),
(1, 6, 'vocabulary', 50, 'reading', 'How do you read 「風」?', '["てんき", "かく", "ゆき", "かぜ"]'::jsonb, 3, '風 is read ''かぜ'' (kaze), meaning ''wind''.', 'medium'),
(1, 6, 'vocabulary', 51, 'meaning', 'What does 「友達」(ともだち) mean?', '["station", "friend", "weather", "train"]'::jsonb, 1, '友達 (ともだち/tomodachi) means ''friend''.', 'easy'),
(1, 6, 'vocabulary', 51, 'reading', 'How do you read 「友達」?', '["ともだち", "てんき", "みず", "まど"]'::jsonb, 0, '友達 is read ''ともだち'' (tomodachi), meaning ''friend''.', 'medium'),
(1, 6, 'vocabulary', 52, 'meaning', 'What does 「家族」(かぞく) mean?', '["family", "door", "room", "vegetable"]'::jsonb, 0, '家族 (かぞく/kazoku) means ''family''.', 'easy'),
(1, 6, 'vocabulary', 52, 'reading', 'How do you read 「家族」?', '["かぞく", "せんしゅう", "せんせい", "ばす"]'::jsonb, 0, '家族 is read ''かぞく'' (kazoku), meaning ''family''.', 'medium'),
(2, 12, 'vocabulary', 53, 'meaning', 'What does 「使う」(つかう) mean?', '["luggage", "to use", "to wait", "easy/kind"]'::jsonb, 1, '使う (つかう/tsukau) means ''to use''.', 'easy'),
(2, 12, 'vocabulary', 53, 'reading', 'How do you read 「使う」?', '["かいぎ", "はたらく", "かなしい", "つかう"]'::jsonb, 3, '使う is read ''つかう'' (tsukau), meaning ''to use''.', 'medium'),
(2, 12, 'vocabulary', 54, 'meaning', 'What does 「働く」(はたらく) mean?', '["to work", "to sit", "airport", "fun"]'::jsonb, 0, '働く (はたらく/hataraku) means ''to work''.', 'easy'),
(2, 12, 'vocabulary', 54, 'reading', 'How do you read 「働く」?', '["けいざい", "しめる", "あける", "はたらく"]'::jsonb, 3, '働く is read ''はたらく'' (hataraku), meaning ''to work''.', 'medium'),
(2, 12, 'vocabulary', 55, 'meaning', 'What does 「走る」(はしる) mean?', '["fun", "to run", "preparation", "to sit"]'::jsonb, 1, '走る (はしる/hashiru) means ''to run''.', 'easy'),
(2, 12, 'vocabulary', 55, 'reading', 'How do you read 「走る」?', '["すわる", "はしる", "くすり", "わすれる"]'::jsonb, 1, '走る is read ''はしる'' (hashiru), meaning ''to run''.', 'medium'),
(2, 12, 'vocabulary', 56, 'meaning', 'What does 「歩く」(あるく) mean?', '["to teach", "to walk", "ticket", "fever"]'::jsonb, 1, '歩く (あるく/aruku) means ''to walk''.', 'easy'),
(2, 12, 'vocabulary', 56, 'reading', 'How do you read 「歩く」?', '["かなしい", "あるく", "つくる", "やくそく"]'::jsonb, 1, '歩く is read ''あるく'' (aruku), meaning ''to walk''.', 'medium'),
(2, 12, 'vocabulary', 57, 'meaning', 'What does 「待つ」(まつ) mean?', '["busy", "preparation", "airport", "to wait"]'::jsonb, 3, '待つ (まつ/matsu) means ''to wait''.', 'easy'),
(2, 12, 'vocabulary', 57, 'reading', 'How do you read 「待つ」?', '["しゅうかん", "まつ", "おわる", "にもつ"]'::jsonb, 1, '待つ is read ''まつ'' (matsu), meaning ''to wait''.', 'medium'),
(2, 12, 'vocabulary', 58, 'meaning', 'What does 「座る」(すわる) mean?', '["preparation", "to wait", "busy", "to sit"]'::jsonb, 3, '座る (すわる/suwaru) means ''to sit''.', 'easy'),
(2, 12, 'vocabulary', 58, 'reading', 'How do you read 「座る」?', '["びょういん", "まつ", "すわる", "あける"]'::jsonb, 2, '座る is read ''すわる'' (suwaru), meaning ''to sit''.', 'medium'),
(2, 12, 'vocabulary', 59, 'meaning', 'What does 「立つ」(たつ) mean?', '["to stand", "to teach", "kind", "medicine"]'::jsonb, 0, '立つ (たつ/tatsu) means ''to stand''.', 'easy'),
(2, 12, 'vocabulary', 59, 'reading', 'How do you read 「立つ」?', '["かなしい", "ふべん", "たつ", "しめる"]'::jsonb, 2, '立つ is read ''たつ'' (tatsu), meaning ''to stand''.', 'medium'),
(2, 12, 'vocabulary', 60, 'meaning', 'What does 「作る」(つくる) mean?', '["easy/kind", "sad", "to make", "inconvenient"]'::jsonb, 2, '作る (つくる/tsukuru) means ''to make''.', 'easy'),
(2, 12, 'vocabulary', 60, 'reading', 'How do you read 「作る」?', '["つくる", "あんぜん", "たいせつ", "べんり"]'::jsonb, 0, '作る is read ''つくる'' (tsukuru), meaning ''to make''.', 'medium'),
(2, 12, 'vocabulary', 61, 'meaning', 'What does 「習う」(ならう) mean?', '["experience", "dangerous", "to use", "to learn"]'::jsonb, 3, '習う (ならう/narau) means ''to learn''.', 'easy'),
(2, 12, 'vocabulary', 61, 'reading', 'How do you read 「習う」?', '["ならう", "じゅんび", "つかう", "かいぎ"]'::jsonb, 0, '習う is read ''ならう'' (narau), meaning ''to learn''.', 'medium'),
(2, 12, 'vocabulary', 62, 'meaning', 'What does 「教える」(おしえる) mean?', '["convenient", "to teach", "hospital", "to wait"]'::jsonb, 1, '教える (おしえる/oshieru) means ''to teach''.', 'easy'),
(2, 12, 'vocabulary', 62, 'reading', 'How do you read 「教える」?', '["おしえる", "やくそく", "たつ", "あるく"]'::jsonb, 0, '教える is read ''おしえる'' (oshieru), meaning ''to teach''.', 'medium'),
(2, 12, 'vocabulary', 63, 'meaning', 'What does 「忘れる」(わすれる) mean?', '["cold (illness)", "to forget", "to teach", "economy"]'::jsonb, 1, '忘れる (わすれる/wasureru) means ''to forget''.', 'easy'),
(2, 12, 'vocabulary', 63, 'reading', 'How do you read 「忘れる」?', '["わすれる", "しんせつ", "むずかしい", "おわる"]'::jsonb, 0, '忘れる is read ''わすれる'' (wasureru), meaning ''to forget''.', 'medium'),
(2, 12, 'vocabulary', 64, 'meaning', 'What does 「覚える」(おぼえる) mean?', '["to memorize", "to open", "to sit", "luggage"]'::jsonb, 0, '覚える (おぼえる/oboeru) means ''to memorize''.', 'easy'),
(2, 12, 'vocabulary', 64, 'reading', 'How do you read 「覚える」?', '["おぼえる", "やさしい", "ねつ", "ならう"]'::jsonb, 0, '覚える is read ''おぼえる'' (oboeru), meaning ''to memorize''.', 'medium'),
(2, 12, 'vocabulary', 65, 'meaning', 'What does 「始まる」(はじまる) mean?', '["luggage", "to forget", "to learn", "to begin (intr.)"]'::jsonb, 3, '始まる (はじまる/hajimaru) means ''to begin (intr.)''.', 'easy'),
(2, 12, 'vocabulary', 65, 'reading', 'How do you read 「始まる」?', '["はじまる", "じゅんび", "しゅうかん", "かいぎ"]'::jsonb, 0, '始まる is read ''はじまる'' (hajimaru), meaning ''to begin (intr.)''.', 'medium'),
(2, 12, 'vocabulary', 66, 'meaning', 'What does 「終わる」(おわる) mean?', '["fun", "luggage", "habit/custom", "to end"]'::jsonb, 3, '終わる (おわる/owaru) means ''to end''.', 'easy'),
(2, 12, 'vocabulary', 66, 'reading', 'How do you read 「終わる」?', '["まつ", "わすれる", "あける", "おわる"]'::jsonb, 3, '終わる is read ''おわる'' (owaru), meaning ''to end''.', 'medium'),
(2, 12, 'vocabulary', 67, 'meaning', 'What does 「開ける」(あける) mean?', '["to open", "easy/kind", "difficult", "dangerous"]'::jsonb, 0, '開ける (あける/akeru) means ''to open''.', 'easy'),
(2, 12, 'vocabulary', 67, 'reading', 'How do you read 「開ける」?', '["すわる", "けいざい", "あける", "おぼえる"]'::jsonb, 2, '開ける is read ''あける'' (akeru), meaning ''to open''.', 'medium'),
(2, 12, 'vocabulary', 68, 'meaning', 'What does 「閉める」(しめる) mean?', '["economy", "experience", "to close", "kind"]'::jsonb, 2, '閉める (しめる/shimeru) means ''to close''.', 'easy'),
(2, 12, 'vocabulary', 68, 'reading', 'How do you read 「閉める」?', '["たいせつ", "はたらく", "べんり", "しめる"]'::jsonb, 3, '閉める is read ''しめる'' (shimeru), meaning ''to close''.', 'medium'),
(2, 12, 'vocabulary', 69, 'meaning', 'What does 「経済」(けいざい) mean?', '["economy", "dangerous", "promise", "convenient"]'::jsonb, 0, '経済 (けいざい/keizai) means ''economy''.', 'easy'),
(2, 12, 'vocabulary', 69, 'reading', 'How do you read 「経済」?', '["ならう", "けいざい", "きっぷ", "しんせつ"]'::jsonb, 1, '経済 is read ''けいざい'' (keizai), meaning ''economy''.', 'medium'),
(2, 12, 'vocabulary', 70, 'meaning', 'What does 「会議」(かいぎ) mean?', '["to close", "inconvenient", "convenient", "meeting"]'::jsonb, 3, '会議 (かいぎ/kaigi) means ''meeting''.', 'easy'),
(2, 12, 'vocabulary', 70, 'reading', 'How do you read 「会議」?', '["はたらく", "ならう", "はしる", "かいぎ"]'::jsonb, 3, '会議 is read ''かいぎ'' (kaigi), meaning ''meeting''.', 'medium'),
(2, 12, 'vocabulary', 71, 'meaning', 'What does 「約束」(やくそく) mean?', '["promise", "to use", "sad", "hospital"]'::jsonb, 0, '約束 (やくそく/yakusoku) means ''promise''.', 'easy'),
(2, 12, 'vocabulary', 71, 'reading', 'How do you read 「約束」?', '["やくそく", "たつ", "やさしい", "しめる"]'::jsonb, 0, '約束 is read ''やくそく'' (yakusoku), meaning ''promise''.', 'medium'),
(2, 12, 'vocabulary', 72, 'meaning', 'What does 「準備」(じゅんび) mean?', '["to stand", "preparation", "busy", "airport"]'::jsonb, 1, '準備 (じゅんび/junbi) means ''preparation''.', 'easy'),
(2, 12, 'vocabulary', 72, 'reading', 'How do you read 「準備」?', '["じゅんび", "ならう", "あける", "つかう"]'::jsonb, 0, '準備 is read ''じゅんび'' (junbi), meaning ''preparation''.', 'medium'),
(2, 12, 'vocabulary', 73, 'meaning', 'What does 「習慣」(しゅうかん) mean?', '["cold (illness)", "to learn", "economy", "habit/custom"]'::jsonb, 3, '習慣 (しゅうかん/shuukan) means ''habit/custom''.', 'easy'),
(2, 12, 'vocabulary', 73, 'reading', 'How do you read 「習慣」?', '["たつ", "じゅんび", "しゅうかん", "まつ"]'::jsonb, 2, '習慣 is read ''しゅうかん'' (shuukan), meaning ''habit/custom''.', 'medium'),
(2, 12, 'vocabulary', 74, 'meaning', 'What does 「経験」(けいけん) mean?', '["experience", "medicine", "to use", "to open"]'::jsonb, 0, '経験 (けいけん/keiken) means ''experience''.', 'easy'),
(2, 12, 'vocabulary', 74, 'reading', 'How do you read 「経験」?', '["しゅうかん", "いそがしい", "けいけん", "かいぎ"]'::jsonb, 2, '経験 is read ''けいけん'' (keiken), meaning ''experience''.', 'medium'),
(2, 12, 'vocabulary', 75, 'meaning', 'What does 「危険」(きけん) mean?', '["luggage", "to close", "to work", "dangerous"]'::jsonb, 3, '危険 (きけん/kiken) means ''dangerous''.', 'easy'),
(2, 12, 'vocabulary', 75, 'reading', 'How do you read 「危険」?', '["あるく", "はたらく", "はじまる", "きけん"]'::jsonb, 3, '危険 is read ''きけん'' (kiken), meaning ''dangerous''.', 'medium'),
(2, 12, 'vocabulary', 76, 'meaning', 'What does 「安全」(あんぜん) mean?', '["to open", "to sit", "economy", "safe"]'::jsonb, 3, '安全 (あんぜん/anzen) means ''safe''.', 'easy'),
(2, 12, 'vocabulary', 76, 'reading', 'How do you read 「安全」?', '["かなしい", "けいけん", "はしる", "あんぜん"]'::jsonb, 3, '安全 is read ''あんぜん'' (anzen), meaning ''safe''.', 'medium'),
(2, 12, 'vocabulary', 77, 'meaning', 'What does 「親切」(しんせつ) mean?', '["promise", "to use", "kind", "to begin (intr.)"]'::jsonb, 2, '親切 (しんせつ/shinsetsu) means ''kind''.', 'easy'),
(2, 12, 'vocabulary', 77, 'reading', 'How do you read 「親切」?', '["あける", "じゅんび", "はじまる", "しんせつ"]'::jsonb, 3, '親切 is read ''しんせつ'' (shinsetsu), meaning ''kind''.', 'medium'),
(2, 12, 'vocabulary', 78, 'meaning', 'What does 「便利」(べんり) mean?', '["to stand", "promise", "fever", "convenient"]'::jsonb, 3, '便利 (べんり/benri) means ''convenient''.', 'easy'),
(2, 12, 'vocabulary', 78, 'reading', 'How do you read 「便利」?', '["かなしい", "べんり", "たいせつ", "あける"]'::jsonb, 1, '便利 is read ''べんり'' (benri), meaning ''convenient''.', 'medium'),
(2, 12, 'vocabulary', 79, 'meaning', 'What does 「不便」(ふべん) mean?', '["to walk", "inconvenient", "to end", "convenient"]'::jsonb, 1, '不便 (ふべん/fuben) means ''inconvenient''.', 'easy'),
(2, 12, 'vocabulary', 79, 'reading', 'How do you read 「不便」?', '["たいせつ", "おぼえる", "あるく", "ふべん"]'::jsonb, 3, '不便 is read ''ふべん'' (fuben), meaning ''inconvenient''.', 'medium'),
(2, 12, 'vocabulary', 80, 'meaning', 'What does 「大切」(たいせつ) mean?', '["to sit", "important", "to make", "to forget"]'::jsonb, 1, '大切 (たいせつ/taisetsu) means ''important''.', 'easy'),
(2, 12, 'vocabulary', 80, 'reading', 'How do you read 「大切」?', '["くうこう", "いそがしい", "たいせつ", "はしる"]'::jsonb, 2, '大切 is read ''たいせつ'' (taisetsu), meaning ''important''.', 'medium'),
(2, 12, 'vocabulary', 81, 'meaning', 'What does 「難しい」(むずかしい) mean?', '["difficult", "easy/kind", "safe", "experience"]'::jsonb, 0, '難しい (むずかしい/muzukashii) means ''difficult''.', 'easy'),
(2, 12, 'vocabulary', 81, 'reading', 'How do you read 「難しい」?', '["かいぎ", "きけん", "すわる", "むずかしい"]'::jsonb, 3, '難しい is read ''むずかしい'' (muzukashii), meaning ''difficult''.', 'medium'),
(2, 12, 'vocabulary', 82, 'meaning', 'What does 「易しい」(やさしい) mean?', '["dangerous", "preparation", "kind", "easy/kind"]'::jsonb, 3, '易しい (やさしい/yasashii) means ''easy/kind''.', 'easy'),
(2, 12, 'vocabulary', 82, 'reading', 'How do you read 「易しい」?', '["あんぜん", "はじまる", "たのしい", "やさしい"]'::jsonb, 3, '易しい is read ''やさしい'' (yasashii), meaning ''easy/kind''.', 'medium'),
(2, 12, 'vocabulary', 83, 'meaning', 'What does 「忙しい」(いそがしい) mean?', '["to work", "fun", "safe", "busy"]'::jsonb, 3, '忙しい (いそがしい/isogashii) means ''busy''.', 'easy'),
(2, 12, 'vocabulary', 83, 'reading', 'How do you read 「忙しい」?', '["やさしい", "しんせつ", "いそがしい", "はしる"]'::jsonb, 2, '忙しい is read ''いそがしい'' (isogashii), meaning ''busy''.', 'medium'),
(2, 12, 'vocabulary', 84, 'meaning', 'What does 「楽しい」(たのしい) mean?', '["to begin (intr.)", "fun", "to wait", "medicine"]'::jsonb, 1, '楽しい (たのしい/tanoshii) means ''fun''.', 'easy'),
(2, 12, 'vocabulary', 84, 'reading', 'How do you read 「楽しい」?', '["けいけん", "ねつ", "たのしい", "はしる"]'::jsonb, 2, '楽しい is read ''たのしい'' (tanoshii), meaning ''fun''.', 'medium'),
(2, 12, 'vocabulary', 85, 'meaning', 'What does 「悲しい」(かなしい) mean?', '["preparation", "to use", "sad", "meeting"]'::jsonb, 2, '悲しい (かなしい/kanashii) means ''sad''.', 'easy'),
(2, 12, 'vocabulary', 85, 'reading', 'How do you read 「悲しい」?', '["たつ", "やさしい", "いそがしい", "かなしい"]'::jsonb, 3, '悲しい is read ''かなしい'' (kanashii), meaning ''sad''.', 'medium'),
(2, 12, 'vocabulary', 86, 'meaning', 'What does 「嬉しい」(うれしい) mean?', '["happy", "to learn", "to memorize", "fun"]'::jsonb, 0, '嬉しい (うれしい/ureshii) means ''happy''.', 'easy'),
(2, 12, 'vocabulary', 86, 'reading', 'How do you read 「嬉しい」?', '["おしえる", "うれしい", "くすり", "しめる"]'::jsonb, 1, '嬉しい is read ''うれしい'' (ureshii), meaning ''happy''.', 'medium'),
(2, 12, 'vocabulary', 87, 'meaning', 'What does 「空港」(くうこう) mean?', '["to sit", "safe", "airport", "medicine"]'::jsonb, 2, '空港 (くうこう/kuukou) means ''airport''.', 'easy'),
(2, 12, 'vocabulary', 87, 'reading', 'How do you read 「空港」?', '["くうこう", "まつ", "ふべん", "しめる"]'::jsonb, 0, '空港 is read ''くうこう'' (kuukou), meaning ''airport''.', 'medium'),
(2, 12, 'vocabulary', 88, 'meaning', 'What does 「旅行」(りょこう) mean?', '["to stand", "travel", "important", "to forget"]'::jsonb, 1, '旅行 (りょこう/ryokou) means ''travel''.', 'easy'),
(2, 12, 'vocabulary', 88, 'reading', 'How do you read 「旅行」?', '["おわる", "たつ", "ふべん", "りょこう"]'::jsonb, 3, '旅行 is read ''りょこう'' (ryokou), meaning ''travel''.', 'medium'),
(2, 12, 'vocabulary', 89, 'meaning', 'What does 「荷物」(にもつ) mean?', '["to learn", "to memorize", "to open", "luggage"]'::jsonb, 3, '荷物 (にもつ/nimotsu) means ''luggage''.', 'easy'),
(2, 12, 'vocabulary', 89, 'reading', 'How do you read 「荷物」?', '["くうこう", "にもつ", "つくる", "やくそく"]'::jsonb, 1, '荷物 is read ''にもつ'' (nimotsu), meaning ''luggage''.', 'medium'),
(2, 12, 'vocabulary', 90, 'meaning', 'What does 「切符」(きっぷ) mean?', '["economy", "to begin (intr.)", "safe", "ticket"]'::jsonb, 3, '切符 (きっぷ/kippu) means ''ticket''.', 'easy'),
(2, 12, 'vocabulary', 90, 'reading', 'How do you read 「切符」?', '["やくそく", "しめる", "きっぷ", "おしえる"]'::jsonb, 2, '切符 is read ''きっぷ'' (kippu), meaning ''ticket''.', 'medium'),
(2, 12, 'vocabulary', 91, 'meaning', 'What does 「病院」(びょういん) mean?', '["hospital", "convenient", "to close", "economy"]'::jsonb, 0, '病院 (びょういん/byouin) means ''hospital''.', 'easy'),
(2, 12, 'vocabulary', 91, 'reading', 'How do you read 「病院」?', '["たつ", "びょういん", "はしる", "やさしい"]'::jsonb, 1, '病院 is read ''びょういん'' (byouin), meaning ''hospital''.', 'medium'),
(2, 12, 'vocabulary', 92, 'meaning', 'What does 「薬」(くすり) mean?', '["safe", "medicine", "difficult", "to run"]'::jsonb, 1, '薬 (くすり/kusuri) means ''medicine''.', 'easy'),
(2, 12, 'vocabulary', 92, 'reading', 'How do you read 「薬」?', '["びょういん", "くすり", "あるく", "はじまる"]'::jsonb, 1, '薬 is read ''くすり'' (kusuri), meaning ''medicine''.', 'medium'),
(2, 12, 'vocabulary', 93, 'meaning', 'What does 「熱」(ねつ) mean?', '["to memorize", "sad", "fever", "difficult"]'::jsonb, 2, '熱 (ねつ/netsu) means ''fever''.', 'easy'),
(2, 12, 'vocabulary', 93, 'reading', 'How do you read 「熱」?', '["かぜ", "ねつ", "たつ", "びょういん"]'::jsonb, 1, '熱 is read ''ねつ'' (netsu), meaning ''fever''.', 'medium'),
(2, 12, 'vocabulary', 94, 'meaning', 'What does 「風邪」(かぜ) mean?', '["to teach", "experience", "cold (illness)", "safe"]'::jsonb, 2, '風邪 (かぜ/kaze) means ''cold (illness)''.', 'easy'),
(2, 12, 'vocabulary', 94, 'reading', 'How do you read 「風邪」?', '["かぜ", "おわる", "びょういん", "はしる"]'::jsonb, 0, '風邪 is read ''かぜ'' (kaze), meaning ''cold (illness)''.', 'medium'),
(3, 17, 'vocabulary', 95, 'meaning', 'What does 「影響」(えいきょう) mean?', '["solution/resolve", "influence/impact", "abundant", "politics"]'::jsonb, 1, '影響 (えいきょう/eikyou) means ''influence/impact''.', 'easy'),
(3, 17, 'vocabulary', 95, 'reading', 'How do you read 「影響」?', '["むじゅん", "しょうきょくてき", "たいさく", "えいきょう"]'::jsonb, 3, '影響 is read ''えいきょう'' (eikyou), meaning ''influence/impact''.', 'medium'),
(3, 17, 'vocabulary', 96, 'meaning', 'What does 「傾向」(けいこう) mean?', '["tendency", "environment", "improvement", "passive"]'::jsonb, 0, '傾向 (けいこう/keikou) means ''tendency''.', 'easy'),
(3, 17, 'vocabulary', 96, 'reading', 'How do you read 「傾向」?', '["たんじゅん", "けいこう", "せいじ", "こうじょう"]'::jsonb, 1, '傾向 is read ''けいこう'' (keikou), meaning ''tendency''.', 'medium'),
(3, 17, 'vocabulary', 97, 'meaning', 'What does 「対策」(たいさく) mean?', '["countermeasure", "maintenance", "explanation", "abundant"]'::jsonb, 0, '対策 (たいさく/taisaku) means ''countermeasure''.', 'easy'),
(3, 17, 'vocabulary', 97, 'reading', 'How do you read 「対策」?', '["えいきょう", "いじ", "たいさく", "せっきょくてき"]'::jsonb, 2, '対策 is read ''たいさく'' (taisaku), meaning ''countermeasure''.', 'medium'),
(3, 17, 'vocabulary', 98, 'meaning', 'What does 「課題」(かだい) mean?', '["culture", "issue/task", "flexible", "improvement"]'::jsonb, 1, '課題 (かだい/kadai) means ''issue/task''.', 'easy'),
(3, 17, 'vocabulary', 98, 'reading', 'How do you read 「課題」?', '["かだい", "きゃっかんてき", "かんきょう", "いじ"]'::jsonb, 0, '課題 is read ''かだい'' (kadai), meaning ''issue/task''.', 'medium'),
(3, 17, 'vocabulary', 99, 'meaning', 'What does 「環境」(かんきょう) mean?', '["environment", "politics", "improvement", "proactive"]'::jsonb, 0, '環境 (かんきょう/kankyou) means ''environment''.', 'easy'),
(3, 17, 'vocabulary', 99, 'reading', 'How do you read 「環境」?', '["たんじゅん", "しゃかい", "ひはん", "かんきょう"]'::jsonb, 3, '環境 is read ''かんきょう'' (kankyou), meaning ''environment''.', 'medium'),
(3, 17, 'vocabulary', 100, 'meaning', 'What does 「社会」(しゃかい) mean?', '["flexible", "politics", "society", "trust"]'::jsonb, 2, '社会 (しゃかい/shakai) means ''society''.', 'easy'),
(3, 17, 'vocabulary', 100, 'reading', 'How do you read 「社会」?', '["しゃかい", "たいさく", "しんらい", "せいじ"]'::jsonb, 0, '社会 is read ''しゃかい'' (shakai), meaning ''society''.', 'medium');

INSERT INTO quiz_questions (level_id, module_id, source_type, source_id, question_type, question_text, options, correct_index, explanation, difficulty) VALUES
(3, 17, 'vocabulary', 101, 'meaning', 'What does 「政治」(せいじ) mean?', '["passive", "politics", "proactive", "culture"]'::jsonb, 1, '政治 (せいじ/seiji) means ''politics''.', 'easy'),
(3, 17, 'vocabulary', 101, 'reading', 'How do you read 「政治」?', '["じつげん", "けいこう", "むじゅん", "せいじ"]'::jsonb, 3, '政治 is read ''せいじ'' (seiji), meaning ''politics''.', 'medium'),
(3, 17, 'vocabulary', 102, 'meaning', 'What does 「文化」(ぶんか) mean?', '["passive", "simple", "contract", "culture"]'::jsonb, 3, '文化 (ぶんか/bunka) means ''culture''.', 'easy'),
(3, 17, 'vocabulary', 102, 'reading', 'How do you read 「文化」?', '["しゃかい", "ぶんか", "きゃっかんてき", "むじゅん"]'::jsonb, 1, '文化 is read ''ぶんか'' (bunka), meaning ''culture''.', 'medium'),
(3, 17, 'vocabulary', 103, 'meaning', 'What does 「契約」(けいやく) mean?', '["society", "contract", "trust", "improvement"]'::jsonb, 1, '契約 (けいやく/keiyaku) means ''contract''.', 'easy'),
(3, 17, 'vocabulary', 103, 'reading', 'How do you read 「契約」?', '["けいやく", "きゃっかんてき", "ぶんか", "じゅうなん"]'::jsonb, 0, '契約 is read ''けいやく'' (keiyaku), meaning ''contract''.', 'medium'),
(3, 17, 'vocabulary', 104, 'meaning', 'What does 「報告」(ほうこく) mean?', '["report", "realization", "objective", "abundant"]'::jsonb, 0, '報告 (ほうこく/houkoku) means ''report''.', 'easy'),
(3, 17, 'vocabulary', 104, 'reading', 'How do you read 「報告」?', '["ひはん", "たんじゅん", "ほうこく", "せっきょくてき"]'::jsonb, 2, '報告 is read ''ほうこく'' (houkoku), meaning ''report''.', 'medium'),
(3, 17, 'vocabulary', 105, 'meaning', 'What does 「説明」(せつめい) mean?', '["report", "culture", "evaluation", "explanation"]'::jsonb, 3, '説明 (せつめい/setsumei) means ''explanation''.', 'easy'),
(3, 17, 'vocabulary', 105, 'reading', 'How do you read 「説明」?', '["しゃかい", "しんらい", "せつめい", "かいぜん"]'::jsonb, 2, '説明 is read ''せつめい'' (setsumei), meaning ''explanation''.', 'medium'),
(3, 17, 'vocabulary', 106, 'meaning', 'What does 「実現」(じつげん) mean?', '["proactive", "culture", "improvement", "realization"]'::jsonb, 3, '実現 (じつげん/jitsugen) means ''realization''.', 'easy'),
(3, 17, 'vocabulary', 106, 'reading', 'How do you read 「実現」?', '["こうじょう", "たいさく", "じつげん", "かだい"]'::jsonb, 2, '実現 is read ''じつげん'' (jitsugen), meaning ''realization''.', 'medium'),
(3, 17, 'vocabulary', 107, 'meaning', 'What does 「解決」(かいけつ) mean?', '["countermeasure", "realization", "passive", "solution/resolve"]'::jsonb, 3, '解決 (かいけつ/kaiketsu) means ''solution/resolve''.', 'easy'),
(3, 17, 'vocabulary', 107, 'reading', 'How do you read 「解決」?', '["かいけつ", "たんじゅん", "かんきょう", "けいこう"]'::jsonb, 0, '解決 is read ''かいけつ'' (kaiketsu), meaning ''solution/resolve''.', 'medium'),
(3, 17, 'vocabulary', 108, 'meaning', 'What does 「向上」(こうじょう) mean?', '["criticism", "proactive", "improvement", "passive"]'::jsonb, 2, '向上 (こうじょう/koujou) means ''improvement''.', 'easy'),
(3, 17, 'vocabulary', 108, 'reading', 'How do you read 「向上」?', '["しょうきょくてき", "かんきょう", "こうじょう", "たんじゅん"]'::jsonb, 2, '向上 is read ''こうじょう'' (koujou), meaning ''improvement''.', 'medium'),
(3, 17, 'vocabulary', 109, 'meaning', 'What does 「維持」(いじ) mean?', '["environment", "maintenance", "politics", "contradiction"]'::jsonb, 1, '維持 (いじ/iji) means ''maintenance''.', 'easy'),
(3, 17, 'vocabulary', 109, 'reading', 'How do you read 「維持」?', '["いじ", "きゃっかんてき", "たいさく", "じつげん"]'::jsonb, 0, '維持 is read ''いじ'' (iji), meaning ''maintenance''.', 'medium'),
(3, 17, 'vocabulary', 110, 'meaning', 'What does 「改善」(かいぜん) mean?', '["simple", "contradiction", "improvement", "contract"]'::jsonb, 2, '改善 (かいぜん/kaizen) means ''improvement''.', 'easy'),
(3, 17, 'vocabulary', 110, 'reading', 'How do you read 「改善」?', '["せいじ", "けいやく", "かいぜん", "ひょうか"]'::jsonb, 2, '改善 is read ''かいぜん'' (kaizen), meaning ''improvement''.', 'medium'),
(3, 17, 'vocabulary', 111, 'meaning', 'What does 「矛盾」(むじゅん) mean?', '["society", "politics", "tendency", "contradiction"]'::jsonb, 3, '矛盾 (むじゅん/mujun) means ''contradiction''.', 'easy'),
(3, 17, 'vocabulary', 111, 'reading', 'How do you read 「矛盾」?', '["かいけつ", "ゆたか", "むじゅん", "せつめい"]'::jsonb, 2, '矛盾 is read ''むじゅん'' (mujun), meaning ''contradiction''.', 'medium'),
(3, 17, 'vocabulary', 112, 'meaning', 'What does 「信頼」(しんらい) mean?', '["trust", "proactive", "contradiction", "tendency"]'::jsonb, 0, '信頼 (しんらい/shinrai) means ''trust''.', 'easy'),
(3, 17, 'vocabulary', 112, 'reading', 'How do you read 「信頼」?', '["けいやく", "ひはん", "たんじゅん", "しんらい"]'::jsonb, 3, '信頼 is read ''しんらい'' (shinrai), meaning ''trust''.', 'medium'),
(3, 17, 'vocabulary', 113, 'meaning', 'What does 「批判」(ひはん) mean?', '["contract", "realization", "criticism", "solution/resolve"]'::jsonb, 2, '批判 (ひはん/hihan) means ''criticism''.', 'easy'),
(3, 17, 'vocabulary', 113, 'reading', 'How do you read 「批判」?', '["ひはん", "いじ", "せっきょくてき", "たいさく"]'::jsonb, 0, '批判 is read ''ひはん'' (hihan), meaning ''criticism''.', 'medium'),
(3, 17, 'vocabulary', 114, 'meaning', 'What does 「評価」(ひょうか) mean?', '["report", "evaluation", "objective", "contradiction"]'::jsonb, 1, '評価 (ひょうか/hyouka) means ''evaluation''.', 'easy'),
(3, 17, 'vocabulary', 114, 'reading', 'How do you read 「評価」?', '["けいこう", "ひょうか", "じゅうなん", "えいきょう"]'::jsonb, 1, '評価 is read ''ひょうか'' (hyouka), meaning ''evaluation''.', 'medium'),
(3, 17, 'vocabulary', 115, 'meaning', 'What does 「複雑」(ふくざつ) mean?', '["evaluation", "simple", "improvement", "complex"]'::jsonb, 3, '複雑 (ふくざつ/fukuzatsu) means ''complex''.', 'easy'),
(3, 17, 'vocabulary', 115, 'reading', 'How do you read 「複雑」?', '["ふくざつ", "けいこう", "かいぜん", "かんきょう"]'::jsonb, 0, '複雑 is read ''ふくざつ'' (fukuzatsu), meaning ''complex''.', 'medium'),
(3, 17, 'vocabulary', 116, 'meaning', 'What does 「単純」(たんじゅん) mean?', '["simple", "influence/impact", "tendency", "criticism"]'::jsonb, 0, '単純 (たんじゅん/tanjun) means ''simple''.', 'easy'),
(3, 17, 'vocabulary', 116, 'reading', 'How do you read 「単純」?', '["むじゅん", "しんらい", "たんじゅん", "じつげん"]'::jsonb, 2, '単純 is read ''たんじゅん'' (tanjun), meaning ''simple''.', 'medium'),
(3, 17, 'vocabulary', 117, 'meaning', 'What does 「豊か」(ゆたか) mean?', '["criticism", "environment", "abundant", "politics"]'::jsonb, 2, '豊か (ゆたか/yutaka) means ''abundant''.', 'easy'),
(3, 17, 'vocabulary', 117, 'reading', 'How do you read 「豊か」?', '["ゆたか", "しゃかい", "えいきょう", "かんきょう"]'::jsonb, 0, '豊か is read ''ゆたか'' (yutaka), meaning ''abundant''.', 'medium'),
(3, 17, 'vocabulary', 118, 'meaning', 'What does 「深刻」(しんこく) mean?', '["maintenance", "serious/grave", "countermeasure", "issue/task"]'::jsonb, 1, '深刻 (しんこく/shinkoku) means ''serious/grave''.', 'easy'),
(3, 17, 'vocabulary', 118, 'reading', 'How do you read 「深刻」?', '["けいやく", "しょうきょくてき", "しんこく", "かいけつ"]'::jsonb, 2, '深刻 is read ''しんこく'' (shinkoku), meaning ''serious/grave''.', 'medium'),
(3, 17, 'vocabulary', 119, 'meaning', 'What does 「柔軟」(じゅうなん) mean?', '["evaluation", "complex", "criticism", "flexible"]'::jsonb, 3, '柔軟 (じゅうなん/juunan) means ''flexible''.', 'easy'),
(3, 17, 'vocabulary', 119, 'reading', 'How do you read 「柔軟」?', '["しゃかい", "えいきょう", "じゅうなん", "ぶんか"]'::jsonb, 2, '柔軟 is read ''じゅうなん'' (juunan), meaning ''flexible''.', 'medium'),
(3, 17, 'vocabulary', 120, 'meaning', 'What does 「積極的」(せっきょくてき) mean?', '["proactive", "culture", "solution/resolve", "society"]'::jsonb, 0, '積極的 (せっきょくてき/sekkyokuteki) means ''proactive''.', 'easy'),
(3, 17, 'vocabulary', 120, 'reading', 'How do you read 「積極的」?', '["しんらい", "せっきょくてき", "えいきょう", "ひょうか"]'::jsonb, 1, '積極的 is read ''せっきょくてき'' (sekkyokuteki), meaning ''proactive''.', 'medium'),
(3, 17, 'vocabulary', 121, 'meaning', 'What does 「消極的」(しょうきょくてき) mean?', '["contradiction", "politics", "evaluation", "passive"]'::jsonb, 3, '消極的 (しょうきょくてき/shoukyokuteki) means ''passive''.', 'easy'),
(3, 17, 'vocabulary', 121, 'reading', 'How do you read 「消極的」?', '["ほうこく", "むじゅん", "しょうきょくてき", "たいさく"]'::jsonb, 2, '消極的 is read ''しょうきょくてき'' (shoukyokuteki), meaning ''passive''.', 'medium'),
(3, 17, 'vocabulary', 122, 'meaning', 'What does 「客観的」(きゃっかんてき) mean?', '["objective", "improvement", "proactive", "serious/grave"]'::jsonb, 0, '客観的 (きゃっかんてき/kyakkanteki) means ''objective''.', 'easy'),
(3, 17, 'vocabulary', 122, 'reading', 'How do you read 「客観的」?', '["いじ", "たいさく", "しんこく", "きゃっかんてき"]'::jsonb, 3, '客観的 is read ''きゃっかんてき'' (kyakkanteki), meaning ''objective''.', 'medium'),
(4, 21, 'vocabulary', 123, 'meaning', 'What does 「概念」(がいねん) mean?', '["premise", "basis/grounds", "concept", "element/factor"]'::jsonb, 2, '概念 (がいねん/gainen) means ''concept''.', 'easy'),
(4, 21, 'vocabulary', 123, 'reading', 'How do you read 「概念」?', '["こんきょ", "ろんり", "しんえん", "がいねん"]'::jsonb, 3, '概念 is read ''がいねん'' (gainen), meaning ''concept''.', 'medium'),
(4, 21, 'vocabulary', 124, 'meaning', 'What does 「本質」(ほんしつ) mean?', '["inevitability", "perspective", "essence", "speculation"]'::jsonb, 2, '本質 (ほんしつ/honshitsu) means ''essence''.', 'easy'),
(4, 21, 'vocabulary', 124, 'reading', 'How do you read 「本質」?', '["ほんしつ", "かんてん", "ぜんてい", "してん"]'::jsonb, 0, '本質 is read ''ほんしつ'' (honshitsu), meaning ''essence''.', 'medium'),
(4, 21, 'vocabulary', 125, 'meaning', 'What does 「論理」(ろんり) mean?', '["promotion (of a process)", "concern/worry", "premise", "logic"]'::jsonb, 3, '論理 (ろんり/ronri) means ''logic''.', 'easy'),
(4, 21, 'vocabulary', 125, 'reading', 'How do you read 「論理」?', '["ろんり", "よくせい", "がいねん", "ぜんてい"]'::jsonb, 0, '論理 is read ''ろんり'' (ronri), meaning ''logic''.', 'medium'),
(4, 21, 'vocabulary', 126, 'meaning', 'What does 「必然性」(ひつぜんせい) mean?', '["inevitability", "viewpoint", "profound", "logic"]'::jsonb, 0, '必然性 (ひつぜんせい/hitsuzensei) means ''inevitability''.', 'easy'),
(4, 21, 'vocabulary', 126, 'reading', 'How do you read 「必然性」?', '["しんえん", "ひつぜんせい", "ようそ", "してん"]'::jsonb, 1, '必然性 is read ''ひつぜんせい'' (hitsuzensei), meaning ''inevitability''.', 'medium'),
(4, 21, 'vocabulary', 127, 'meaning', 'What does 「要素」(ようそ) mean?', '["essence", "element/factor", "background", "concept"]'::jsonb, 1, '要素 (ようそ/youso) means ''element/factor''.', 'easy'),
(4, 21, 'vocabulary', 127, 'reading', 'How do you read 「要素」?', '["ようそ", "ほんしつ", "ふきゅう", "ろんり"]'::jsonb, 0, '要素 is read ''ようそ'' (youso), meaning ''element/factor''.', 'medium'),
(4, 21, 'vocabulary', 128, 'meaning', 'What does 「背景」(はいけい) mean?', '["background", "premise", "promotion (of a process)", "inevitability"]'::jsonb, 0, '背景 (はいけい/haikei) means ''background''.', 'easy'),
(4, 21, 'vocabulary', 128, 'reading', 'How do you read 「背景」?', '["はいけい", "ほんしつ", "しんえん", "ろんり"]'::jsonb, 0, '背景 is read ''はいけい'' (haikei), meaning ''background''.', 'medium'),
(4, 21, 'vocabulary', 129, 'meaning', 'What does 「視点」(してん) mean?', '["element/factor", "viewpoint", "inevitability", "perspective"]'::jsonb, 1, '視点 (してん/shiten) means ''viewpoint''.', 'easy'),
(4, 21, 'vocabulary', 129, 'reading', 'How do you read 「視点」?', '["よくせい", "してん", "こんきょ", "がいねん"]'::jsonb, 1, '視点 is read ''してん'' (shiten), meaning ''viewpoint''.', 'medium'),
(4, 21, 'vocabulary', 130, 'meaning', 'What does 「観点」(かんてん) mean?', '["concern/worry", "essence", "widespread adoption", "perspective"]'::jsonb, 3, '観点 (かんてん/kanten) means ''perspective''.', 'easy'),
(4, 21, 'vocabulary', 130, 'reading', 'How do you read 「観点」?', '["かんてん", "しんえん", "がいねん", "よくせい"]'::jsonb, 0, '観点 is read ''かんてん'' (kanten), meaning ''perspective''.', 'medium'),
(4, 21, 'vocabulary', 131, 'meaning', 'What does 「前提」(ぜんてい) mean?', '["premise", "valid/appropriate", "viewpoint", "essence"]'::jsonb, 0, '前提 (ぜんてい/zentei) means ''premise''.', 'easy'),
(4, 21, 'vocabulary', 131, 'reading', 'How do you read 「前提」?', '["がいねん", "はいけい", "ぜんてい", "よくせい"]'::jsonb, 2, '前提 is read ''ぜんてい'' (zentei), meaning ''premise''.', 'medium'),
(4, 21, 'vocabulary', 132, 'meaning', 'What does 「根拠」(こんきょ) mean?', '["remarkable/notable", "basis/grounds", "widespread adoption", "concept"]'::jsonb, 1, '根拠 (こんきょ/konkyo) means ''basis/grounds''.', 'easy'),
(4, 21, 'vocabulary', 132, 'reading', 'How do you read 「根拠」?', '["ふきゅう", "けんちょ", "こんきょ", "あいまい"]'::jsonb, 2, '根拠 is read ''こんきょ'' (konkyo), meaning ''basis/grounds''.', 'medium'),
(4, 21, 'vocabulary', 133, 'meaning', 'What does 「推測」(すいそく) mean?', '["viewpoint", "perspective", "basis/grounds", "speculation"]'::jsonb, 3, '推測 (すいそく/suisoku) means ''speculation''.', 'easy'),
(4, 21, 'vocabulary', 133, 'reading', 'How do you read 「推測」?', '["すいそく", "ろんり", "けんちょ", "ひつぜんせい"]'::jsonb, 0, '推測 is read ''すいそく'' (suisoku), meaning ''speculation''.', 'medium'),
(4, 21, 'vocabulary', 134, 'meaning', 'What does 「懸念」(けねん) mean?', '["profound", "promotion (of a process)", "logic", "concern/worry"]'::jsonb, 3, '懸念 (けねん/kenen) means ''concern/worry''.', 'easy'),
(4, 21, 'vocabulary', 134, 'reading', 'How do you read 「懸念」?', '["けねん", "ふきゅう", "してん", "こんきょ"]'::jsonb, 0, '懸念 is read ''けねん'' (kenen), meaning ''concern/worry''.', 'medium'),
(4, 21, 'vocabulary', 135, 'meaning', 'What does 「普及」(ふきゅう) mean?', '["widespread adoption", "promotion (of a process)", "correction/rectification", "perspective"]'::jsonb, 0, '普及 (ふきゅう/fukyuu) means ''widespread adoption''.', 'easy'),
(4, 21, 'vocabulary', 135, 'reading', 'How do you read 「普及」?', '["けねん", "あいまい", "ふきゅう", "すいそく"]'::jsonb, 2, '普及 is read ''ふきゅう'' (fukyuu), meaning ''widespread adoption''.', 'medium'),
(4, 21, 'vocabulary', 136, 'meaning', 'What does 「促進」(そくしん) mean?', '["correction/rectification", "background", "promotion (of a process)", "valid/appropriate"]'::jsonb, 2, '促進 (そくしん/sokushin) means ''promotion (of a process)''.', 'easy'),
(4, 21, 'vocabulary', 136, 'reading', 'How do you read 「促進」?', '["そくしん", "ようそ", "ぜせい", "すいそく"]'::jsonb, 0, '促進 is read ''そくしん'' (sokushin), meaning ''promotion (of a process)''.', 'medium'),
(4, 21, 'vocabulary', 137, 'meaning', 'What does 「抑制」(よくせい) mean?', '["element/factor", "suppression/restraint", "premise", "basis/grounds"]'::jsonb, 1, '抑制 (よくせい/yokusei) means ''suppression/restraint''.', 'easy'),
(4, 21, 'vocabulary', 137, 'reading', 'How do you read 「抑制」?', '["はいけい", "あいまい", "よくせい", "けねん"]'::jsonb, 2, '抑制 is read ''よくせい'' (yokusei), meaning ''suppression/restraint''.', 'medium'),
(4, 21, 'vocabulary', 138, 'meaning', 'What does 「是正」(ぜせい) mean?', '["background", "inevitability", "correction/rectification", "premise"]'::jsonb, 2, '是正 (ぜせい/zesei) means ''correction/rectification''.', 'easy'),
(4, 21, 'vocabulary', 138, 'reading', 'How do you read 「是正」?', '["ようそ", "ぜせい", "しんえん", "こんきょ"]'::jsonb, 1, '是正 is read ''ぜせい'' (zesei), meaning ''correction/rectification''.', 'medium'),
(4, 21, 'vocabulary', 139, 'meaning', 'What does 「顕著」(けんちょ) mean?', '["remarkable/notable", "inevitability", "viewpoint", "valid/appropriate"]'::jsonb, 0, '顕著 (けんちょ/kencho) means ''remarkable/notable''.', 'easy'),
(4, 21, 'vocabulary', 139, 'reading', 'How do you read 「顕著」?', '["がいねん", "よくせい", "ほんしつ", "けんちょ"]'::jsonb, 3, '顕著 is read ''けんちょ'' (kencho), meaning ''remarkable/notable''.', 'medium'),
(4, 21, 'vocabulary', 140, 'meaning', 'What does 「曖昧」(あいまい) mean?', '["suppression/restraint", "basis/grounds", "ambiguous", "remarkable/notable"]'::jsonb, 2, '曖昧 (あいまい/aimai) means ''ambiguous''.', 'easy'),
(4, 21, 'vocabulary', 140, 'reading', 'How do you read 「曖昧」?', '["ふきゅう", "がいねん", "かんてん", "あいまい"]'::jsonb, 3, '曖昧 is read ''あいまい'' (aimai), meaning ''ambiguous''.', 'medium'),
(4, 21, 'vocabulary', 141, 'meaning', 'What does 「妥当」(だとう) mean?', '["valid/appropriate", "background", "profound", "perspective"]'::jsonb, 0, '妥当 (だとう/datou) means ''valid/appropriate''.', 'easy'),
(4, 21, 'vocabulary', 141, 'reading', 'How do you read 「妥当」?', '["ひつぜんせい", "ぜんてい", "すいそく", "だとう"]'::jsonb, 3, '妥当 is read ''だとう'' (datou), meaning ''valid/appropriate''.', 'medium'),
(4, 21, 'vocabulary', 142, 'meaning', 'What does 「深遠」(しんえん) mean?', '["promotion (of a process)", "background", "premise", "profound"]'::jsonb, 3, '深遠 (しんえん/shin''en) means ''profound''.', 'easy'),
(4, 21, 'vocabulary', 142, 'reading', 'How do you read 「深遠」?', '["しんえん", "けんちょ", "そくしん", "はいけい"]'::jsonb, 0, '深遠 is read ''しんえん'' (shin''en), meaning ''profound''.', 'medium'),
(5, 25, 'vocabulary', 143, 'meaning', 'What does 「矛盾」(むじゅん) mean?', '["skepticism", "right and wrong / by all means", "contradiction", "inevitability"]'::jsonb, 2, '矛盾 (むじゅん/mujun) means ''contradiction''.', 'easy'),
(5, 25, 'vocabulary', 143, 'reading', 'How do you read 「矛盾」?', '["むじゅん", "せつなてき", "どうさつ", "ほうせつ"]'::jsonb, 0, '矛盾 is read ''むじゅん'' (mujun), meaning ''contradiction''.', 'medium'),
(5, 25, 'vocabulary', 144, 'meaning', 'What does 「必然」(ひつぜん) mean?', '["inevitability", "subsumption/inclusion", "right and wrong / by all means", "beginning/clue"]'::jsonb, 0, '必然 (ひつぜん/hitsuzen) means ''inevitability''.', 'easy'),
(5, 25, 'vocabulary', 144, 'reading', 'How do you read 「必然」?', '["しさ", "へいがい", "たんしょ", "ひつぜん"]'::jsonb, 3, '必然 is read ''ひつぜん'' (hitsuzen), meaning ''inevitability''.', 'medium'),
(5, 25, 'vocabulary', 145, 'meaning', 'What does 「懐疑」(かいぎ) mean?', '["beginning/clue", "harmful effect", "skepticism", "inevitability"]'::jsonb, 2, '懐疑 (かいぎ/kaigi) means ''skepticism''.', 'easy'),
(5, 25, 'vocabulary', 145, 'reading', 'How do you read 「懐疑」?', '["かくいつてき", "へいがい", "いつだつ", "かいぎ"]'::jsonb, 3, '懐疑 is read ''かいぎ'' (kaigi), meaning ''skepticism''.', 'medium'),
(5, 25, 'vocabulary', 146, 'meaning', 'What does 「洞察」(どうさつ) mean?', '["inevitability", "harmful effect", "insight", "momentary/fleeting"]'::jsonb, 2, '洞察 (どうさつ/dousatsu) means ''insight''.', 'easy'),
(5, 25, 'vocabulary', 146, 'reading', 'How do you read 「洞察」?', '["ほうせつ", "ひつぜん", "いつだつ", "どうさつ"]'::jsonb, 3, '洞察 is read ''どうさつ'' (dousatsu), meaning ''insight''.', 'medium'),
(5, 25, 'vocabulary', 147, 'meaning', 'What does 「包摂」(ほうせつ) mean?', '["subsumption/inclusion", "right and wrong / by all means", "uniform/standardized", "harmful effect"]'::jsonb, 0, '包摂 (ほうせつ/housetsu) means ''subsumption/inclusion''.', 'easy'),
(5, 25, 'vocabulary', 147, 'reading', 'How do you read 「包摂」?', '["しいてき", "かくいつてき", "ほうせつ", "ひつぜん"]'::jsonb, 2, '包摂 is read ''ほうせつ'' (housetsu), meaning ''subsumption/inclusion''.', 'medium'),
(5, 25, 'vocabulary', 148, 'meaning', 'What does 「逸脱」(いつだつ) mean?', '["skepticism", "arbitrary", "suggestion/implication", "deviation"]'::jsonb, 3, '逸脱 (いつだつ/itsudatsu) means ''deviation''.', 'easy'),
(5, 25, 'vocabulary', 148, 'reading', 'How do you read 「逸脱」?', '["かくいつてき", "しいてき", "いつだつ", "たんしょ"]'::jsonb, 2, '逸脱 is read ''いつだつ'' (itsudatsu), meaning ''deviation''.', 'medium'),
(5, 25, 'vocabulary', 149, 'meaning', 'What does 「示唆」(しさ) mean?', '["uniform/standardized", "insight", "subsumption/inclusion", "suggestion/implication"]'::jsonb, 3, '示唆 (しさ/shisa) means ''suggestion/implication''.', 'easy'),
(5, 25, 'vocabulary', 149, 'reading', 'How do you read 「示唆」?', '["かいぎ", "しいてき", "へいがい", "しさ"]'::jsonb, 3, '示唆 is read ''しさ'' (shisa), meaning ''suggestion/implication''.', 'medium'),
(5, 25, 'vocabulary', 150, 'meaning', 'What does 「弊害」(へいがい) mean?', '["deviation", "harmful effect", "insight", "arbitrary"]'::jsonb, 1, '弊害 (へいがい/heigai) means ''harmful effect''.', 'easy'),
(5, 25, 'vocabulary', 150, 'reading', 'How do you read 「弊害」?', '["へいがい", "しさ", "ふへんてき", "ぜひ"]'::jsonb, 0, '弊害 is read ''へいがい'' (heigai), meaning ''harmful effect''.', 'medium'),
(5, 25, 'vocabulary', 151, 'meaning', 'What does 「是非」(ぜひ) mean?', '["suggestion/implication", "subsumption/inclusion", "right and wrong / by all means", "skepticism"]'::jsonb, 2, '是非 (ぜひ/zehi) means ''right and wrong / by all means''.', 'easy'),
(5, 25, 'vocabulary', 151, 'reading', 'How do you read 「是非」?', '["かいぎ", "かくいつてき", "ぜひ", "たんしょ"]'::jsonb, 2, '是非 is read ''ぜひ'' (zehi), meaning ''right and wrong / by all means''.', 'medium'),
(5, 25, 'vocabulary', 152, 'meaning', 'What does 「端緒」(たんしょ) mean?', '["beginning/clue", "contradiction", "insight", "arbitrary"]'::jsonb, 0, '端緒 (たんしょ/tansho) means ''beginning/clue''.', 'easy'),
(5, 25, 'vocabulary', 152, 'reading', 'How do you read 「端緒」?', '["たんしょ", "ひつぜん", "ほうせつ", "ふへんてき"]'::jsonb, 0, '端緒 is read ''たんしょ'' (tansho), meaning ''beginning/clue''.', 'medium'),
(5, 25, 'vocabulary', 153, 'meaning', 'What does 「普遍的」(ふへんてき) mean?', '["deviation", "universal", "uniform/standardized", "harmful effect"]'::jsonb, 1, '普遍的 (ふへんてき/fuhenteki) means ''universal''.', 'easy'),
(5, 25, 'vocabulary', 153, 'reading', 'How do you read 「普遍的」?', '["ふへんてき", "ぜひ", "かいぎ", "かくいつてき"]'::jsonb, 0, '普遍的 is read ''ふへんてき'' (fuhenteki), meaning ''universal''.', 'medium'),
(5, 25, 'vocabulary', 154, 'meaning', 'What does 「恣意的」(しいてき) mean?', '["arbitrary", "harmful effect", "uniform/standardized", "insight"]'::jsonb, 0, '恣意的 (しいてき/shiiteki) means ''arbitrary''.', 'easy'),
(5, 25, 'vocabulary', 154, 'reading', 'How do you read 「恣意的」?', '["しいてき", "ぜひ", "ひつぜん", "ふへんてき"]'::jsonb, 0, '恣意的 is read ''しいてき'' (shiiteki), meaning ''arbitrary''.', 'medium'),
(5, 25, 'vocabulary', 155, 'meaning', 'What does 「刹那的」(せつなてき) mean?', '["skepticism", "insight", "harmful effect", "momentary/fleeting"]'::jsonb, 3, '刹那的 (せつなてき/setsunateki) means ''momentary/fleeting''.', 'easy'),
(5, 25, 'vocabulary', 155, 'reading', 'How do you read 「刹那的」?', '["かいぎ", "かくいつてき", "へいがい", "せつなてき"]'::jsonb, 3, '刹那的 is read ''せつなてき'' (setsunateki), meaning ''momentary/fleeting''.', 'medium'),
(5, 25, 'vocabulary', 156, 'meaning', 'What does 「画一的」(かくいつてき) mean?', '["beginning/clue", "right and wrong / by all means", "uniform/standardized", "skepticism"]'::jsonb, 2, '画一的 (かくいつてき/kakuitsuteki) means ''uniform/standardized''.', 'easy'),
(5, 25, 'vocabulary', 156, 'reading', 'How do you read 「画一的」?', '["へいがい", "しいてき", "たんしょ", "かくいつてき"]'::jsonb, 3, '画一的 is read ''かくいつてき'' (kakuitsuteki), meaning ''uniform/standardized''.', 'medium'),
(1, 6, 'kanji', 1, 'meaning', 'What does the kanji 「一」mean?', '["school/study", "to drink", "to come", "one"]'::jsonb, 3, '一 means ''one'' (on: イチ, kun: ひと.つ).', 'medium'),
(1, 6, 'kanji', 2, 'meaning', 'What does the kanji 「二」mean?', '["school/study", "two", "three", "ten-thousand"]'::jsonb, 1, '二 means ''two'' (on: ニ, kun: ふた.つ).', 'medium'),
(1, 6, 'kanji', 3, 'meaning', 'What does the kanji 「三」mean?', '["to read", "person", "eight", "three"]'::jsonb, 3, '三 means ''three'' (on: サン, kun: みっ.つ).', 'medium'),
(1, 6, 'kanji', 4, 'meaning', 'What does the kanji 「四」mean?', '["to go", "three", "four", "month/moon"]'::jsonb, 2, '四 means ''four'' (on: シ, kun: よっ.つ).', 'medium'),
(1, 6, 'kanji', 5, 'meaning', 'What does the kanji 「五」mean?', '["school/study", "to see", "five", "person"]'::jsonb, 2, '五 means ''five'' (on: ゴ, kun: いつ.つ).', 'medium'),
(1, 6, 'kanji', 6, 'meaning', 'What does the kanji 「六」mean?', '["six", "tree/wood", "to come", "person"]'::jsonb, 0, '六 means ''six'' (on: ロク, kun: むっ.つ).', 'medium'),
(1, 6, 'kanji', 7, 'meaning', 'What does the kanji 「七」mean?', '["name", "to hear/ask", "seven", "company/meet"]'::jsonb, 2, '七 means ''seven'' (on: シチ, kun: なな.つ).', 'medium'),
(1, 6, 'kanji', 8, 'meaning', 'What does the kanji 「八」mean?', '["month/moon", "name", "to read", "eight"]'::jsonb, 3, '八 means ''eight'' (on: ハチ, kun: やっ.つ).', 'medium'),
(1, 6, 'kanji', 9, 'meaning', 'What does the kanji 「九」mean?', '["nine", "day/sun", "year", "now"]'::jsonb, 0, '九 means ''nine'' (on: キュウ, kun: ここの.つ).', 'medium'),
(1, 6, 'kanji', 10, 'meaning', 'What does the kanji 「十」mean?', '["ten", "to speak", "company/meet", "three"]'::jsonb, 0, '十 means ''ten'' (on: ジュウ, kun: とお).', 'medium'),
(1, 6, 'kanji', 11, 'meaning', 'What does the kanji 「百」mean?', '["three", "seven", "hundred", "one"]'::jsonb, 2, '百 means ''hundred'' (on: ヒャク, kun: -).', 'medium'),
(1, 6, 'kanji', 12, 'meaning', 'What does the kanji 「千」mean?', '["thousand", "to read", "teacher/before", "to speak"]'::jsonb, 0, '千 means ''thousand'' (on: セン, kun: -).', 'medium'),
(1, 6, 'kanji', 13, 'meaning', 'What does the kanji 「万」mean?', '["ten-thousand", "to drink", "month/moon", "three"]'::jsonb, 0, '万 means ''ten-thousand'' (on: マン, kun: -).', 'medium'),
(1, 6, 'kanji', 14, 'meaning', 'What does the kanji 「日」mean?', '["seven", "day/sun", "to go", "three"]'::jsonb, 1, '日 means ''day/sun'' (on: ニチ, kun: ひ).', 'medium'),
(1, 6, 'kanji', 15, 'meaning', 'What does the kanji 「月」mean?', '["thousand", "tree/wood", "year", "month/moon"]'::jsonb, 3, '月 means ''month/moon'' (on: ゲツ, kun: つき).', 'medium'),
(1, 6, 'kanji', 16, 'meaning', 'What does the kanji 「火」mean?', '["to come", "two", "four", "fire"]'::jsonb, 3, '火 means ''fire'' (on: カ, kun: ひ).', 'medium'),
(1, 6, 'kanji', 17, 'meaning', 'What does the kanji 「水」mean?', '["to go", "company/meet", "eight", "water"]'::jsonb, 3, '水 means ''water'' (on: スイ, kun: みず).', 'medium'),
(1, 6, 'kanji', 18, 'meaning', 'What does the kanji 「木」mean?', '["ten", "teacher/before", "to see", "tree/wood"]'::jsonb, 3, '木 means ''tree/wood'' (on: モク, kun: き).', 'medium'),
(1, 6, 'kanji', 19, 'meaning', 'What does the kanji 「金」mean?', '["gold/money", "six", "day/sun", "to see"]'::jsonb, 0, '金 means ''gold/money'' (on: キン, kun: かね).', 'medium'),
(1, 6, 'kanji', 20, 'meaning', 'What does the kanji 「土」mean?', '["one", "eight", "earth/soil", "to come"]'::jsonb, 2, '土 means ''earth/soil'' (on: ド, kun: つち).', 'medium'),
(1, 6, 'kanji', 21, 'meaning', 'What does the kanji 「年」mean?', '["to see", "nine", "year", "two"]'::jsonb, 2, '年 means ''year'' (on: ネン, kun: とし).', 'medium'),
(1, 6, 'kanji', 22, 'meaning', 'What does the kanji 「今」mean?', '["thousand", "to eat", "now", "four"]'::jsonb, 2, '今 means ''now'' (on: コン, kun: いま).', 'medium'),
(1, 6, 'kanji', 23, 'meaning', 'What does the kanji 「人」mean?', '["six", "gold/money", "to hear/ask", "person"]'::jsonb, 3, '人 means ''person'' (on: ジン, kun: ひと).', 'medium'),
(1, 6, 'kanji', 24, 'meaning', 'What does the kanji 「名前」mean?', '["three", "one", "name", "four"]'::jsonb, 2, '名前 means ''name'' (on: メイ, kun: なまえ).', 'medium'),
(1, 6, 'kanji', 25, 'meaning', 'What does the kanji 「学校」mean?', '["earth/soil", "teacher/before", "hundred", "school/study"]'::jsonb, 3, '学校 means ''school/study'' (on: ガク, kun: まな.ぶ).', 'medium'),
(1, 6, 'kanji', 26, 'meaning', 'What does the kanji 「先生」mean?', '["name", "year", "to eat", "teacher/before"]'::jsonb, 3, '先生 means ''teacher/before'' (on: セン, kun: さき).', 'medium'),
(1, 6, 'kanji', 27, 'meaning', 'What does the kanji 「会社」mean?', '["ten", "company/meet", "name", "eight"]'::jsonb, 1, '会社 means ''company/meet'' (on: カイ, kun: あ.う).', 'medium'),
(1, 6, 'kanji', 28, 'meaning', 'What does the kanji 「行く」mean?', '["to see", "school/study", "to go", "to eat"]'::jsonb, 2, '行く means ''to go'' (on: コウ, kun: い.く).', 'medium'),
(1, 6, 'kanji', 29, 'meaning', 'What does the kanji 「来る」mean?', '["tree/wood", "gold/money", "to come", "four"]'::jsonb, 2, '来る means ''to come'' (on: ライ, kun: く.る).', 'medium'),
(1, 6, 'kanji', 30, 'meaning', 'What does the kanji 「食べる」mean?', '["ten", "to go", "to eat", "earth/soil"]'::jsonb, 2, '食べる means ''to eat'' (on: ショク, kun: た.べる).', 'medium'),
(1, 6, 'kanji', 31, 'meaning', 'What does the kanji 「飲む」mean?', '["month/moon", "school/study", "to drink", "to come"]'::jsonb, 2, '飲む means ''to drink'' (on: イン, kun: の.む).', 'medium'),
(1, 6, 'kanji', 32, 'meaning', 'What does the kanji 「見る」mean?', '["water", "tree/wood", "year", "to see"]'::jsonb, 3, '見る means ''to see'' (on: ケン, kun: み.る).', 'medium'),
(1, 6, 'kanji', 33, 'meaning', 'What does the kanji 「聞く」mean?', '["tree/wood", "gold/money", "ten", "to hear/ask"]'::jsonb, 3, '聞く means ''to hear/ask'' (on: ブン, kun: き.く).', 'medium'),
(1, 6, 'kanji', 34, 'meaning', 'What does the kanji 「読む」mean?', '["to read", "to speak", "school/study", "to see"]'::jsonb, 0, '読む means ''to read'' (on: ドク, kun: よ.む).', 'medium'),
(1, 6, 'kanji', 35, 'meaning', 'What does the kanji 「書く」mean?', '["four", "earth/soil", "teacher/before", "to write"]'::jsonb, 3, '書く means ''to write'' (on: ショ, kun: か.く).', 'medium'),
(1, 6, 'kanji', 36, 'meaning', 'What does the kanji 「話す」mean?', '["one", "water", "school/study", "to speak"]'::jsonb, 3, '話す means ''to speak'' (on: ワ, kun: はな.す).', 'medium'),
(2, 12, 'kanji', 37, 'meaning', 'What does the kanji 「使う」mean?', '["preparation", "to walk", "to use", "sea"]'::jsonb, 2, '使う means ''to use'' (on: シ, kun: つか.う).', 'medium'),
(2, 12, 'kanji', 38, 'meaning', 'What does the kanji 「働く」mean?', '["to work", "meeting/council", "promise", "mountain"]'::jsonb, 0, '働く means ''to work'' (on: ドウ, kun: はたら.く).', 'medium'),
(2, 12, 'kanji', 39, 'meaning', 'What does the kanji 「走る」mean?', '["old", "to run", "to walk", "new"]'::jsonb, 1, '走る means ''to run'' (on: ソウ, kun: はし.る).', 'medium'),
(2, 12, 'kanji', 40, 'meaning', 'What does the kanji 「歩く」mean?', '["early/fast", "to walk", "sky", "promise"]'::jsonb, 1, '歩く means ''to walk'' (on: ホ, kun: ある.く).', 'medium'),
(2, 12, 'kanji', 41, 'meaning', 'What does the kanji 「待つ」mean?', '["to walk", "safety", "sea", "to wait"]'::jsonb, 3, '待つ means ''to wait'' (on: タイ, kun: ま.つ).', 'medium'),
(2, 12, 'kanji', 42, 'meaning', 'What does the kanji 「早い」mean?', '["early/fast", "mountain", "danger", "to use"]'::jsonb, 0, '早い means ''early/fast'' (on: ソウ, kun: はや.い).', 'medium'),
(2, 12, 'kanji', 43, 'meaning', 'What does the kanji 「新しい」mean?', '["to work", "to walk", "old", "new"]'::jsonb, 3, '新しい means ''new'' (on: シン, kun: あたら.しい).', 'medium'),
(2, 12, 'kanji', 44, 'meaning', 'What does the kanji 「古い」mean?', '["weather/heaven", "cheap", "to walk", "old"]'::jsonb, 3, '古い means ''old'' (on: コ, kun: ふる.い).', 'medium'),
(2, 12, 'kanji', 45, 'meaning', 'What does the kanji 「高い」mean?', '["mountain", "tall/expensive", "cheap", "to work"]'::jsonb, 1, '高い means ''tall/expensive'' (on: コウ, kun: たか.い).', 'medium'),
(2, 12, 'kanji', 46, 'meaning', 'What does the kanji 「安い」mean?', '["cheap", "to use", "to work", "to run"]'::jsonb, 0, '安い means ''cheap'' (on: アン, kun: やす.い).', 'medium'),
(2, 12, 'kanji', 47, 'meaning', 'What does the kanji 「川」mean?', '["river", "economy", "meeting/council", "convenience"]'::jsonb, 0, '川 means ''river'' (on: セン, kun: かわ).', 'medium'),
(2, 12, 'kanji', 48, 'meaning', 'What does the kanji 「山」mean?', '["mountain", "to walk", "convenience", "to run"]'::jsonb, 0, '山 means ''mountain'' (on: サン, kun: やま).', 'medium'),
(2, 12, 'kanji', 49, 'meaning', 'What does the kanji 「海」mean?', '["kindness", "to run", "safety", "sea"]'::jsonb, 3, '海 means ''sea'' (on: カイ, kun: うみ).', 'medium'),
(2, 12, 'kanji', 50, 'meaning', 'What does the kanji 「空」mean?', '["sky", "old", "early/fast", "mountain"]'::jsonb, 0, '空 means ''sky'' (on: クウ, kun: そら).', 'medium'),
(2, 12, 'kanji', 51, 'meaning', 'What does the kanji 「天気」mean?', '["to work", "mountain", "weather/heaven", "tall/expensive"]'::jsonb, 2, '天気 means ''weather/heaven'' (on: テン, kun: あめ).', 'medium'),
(2, 12, 'kanji', 52, 'meaning', 'What does the kanji 「経済」mean?', '["convenience", "safety", "promise", "economy"]'::jsonb, 3, '経済 means ''economy'' (on: ケイ, kun: -).', 'medium'),
(2, 12, 'kanji', 53, 'meaning', 'What does the kanji 「会議」mean?', '["to wait", "meeting/council", "to use", "river"]'::jsonb, 1, '会議 means ''meeting/council'' (on: ギ, kun: -).', 'medium'),
(2, 12, 'kanji', 54, 'meaning', 'What does the kanji 「約束」mean?', '["promise", "safety", "weather/heaven", "experience"]'::jsonb, 0, '約束 means ''promise'' (on: ヤク, kun: -).', 'medium'),
(2, 12, 'kanji', 55, 'meaning', 'What does the kanji 「準備」mean?', '["preparation", "sea", "tall/expensive", "mountain"]'::jsonb, 0, '準備 means ''preparation'' (on: ジュン, kun: -).', 'medium'),
(2, 12, 'kanji', 56, 'meaning', 'What does the kanji 「経験」mean?', '["experience", "weather/heaven", "sea", "early/fast"]'::jsonb, 0, '経験 means ''experience'' (on: ケン, kun: -).', 'medium'),
(2, 12, 'kanji', 57, 'meaning', 'What does the kanji 「危険」mean?', '["convenience", "new", "danger", "weather/heaven"]'::jsonb, 2, '危険 means ''danger'' (on: キ, kun: あぶ.ない).', 'medium'),
(2, 12, 'kanji', 58, 'meaning', 'What does the kanji 「安全」mean?', '["mountain", "to run", "safety", "experience"]'::jsonb, 2, '安全 means ''safety'' (on: ゼン, kun: まった.い).', 'medium'),
(2, 12, 'kanji', 59, 'meaning', 'What does the kanji 「親切」mean?', '["kindness", "danger", "to use", "sea"]'::jsonb, 0, '親切 means ''kindness'' (on: シン, kun: おや).', 'medium'),
(2, 12, 'kanji', 60, 'meaning', 'What does the kanji 「便利」mean?', '["convenience", "old", "economy", "river"]'::jsonb, 0, '便利 means ''convenience'' (on: ベン, kun: -).', 'medium'),
(3, 17, 'kanji', 61, 'meaning', 'What does the kanji 「影響」mean?', '["environment", "politics", "influence", "task/subject"]'::jsonb, 2, '影響 means ''influence'' (on: エイ, kun: かげ).', 'medium'),
(3, 17, 'kanji', 62, 'meaning', 'What does the kanji 「傾向」mean?', '["report", "contract", "tendency", "task/subject"]'::jsonb, 2, '傾向 means ''tendency'' (on: ケイ, kun: かたむ.く).', 'medium'),
(3, 17, 'kanji', 63, 'meaning', 'What does the kanji 「対策」mean?', '["countermeasure", "task/subject", "environment", "culture"]'::jsonb, 0, '対策 means ''countermeasure'' (on: タイ, kun: こた.える).', 'medium'),
(3, 17, 'kanji', 64, 'meaning', 'What does the kanji 「課題」mean?', '["task/subject", "politics", "improvement", "countermeasure"]'::jsonb, 0, '課題 means ''task/subject'' (on: カ, kun: -).', 'medium'),
(3, 17, 'kanji', 65, 'meaning', 'What does the kanji 「環境」mean?', '["contract", "maintain", "environment", "politics"]'::jsonb, 2, '環境 means ''environment'' (on: カン, kun: わ).', 'medium'),
(3, 17, 'kanji', 66, 'meaning', 'What does the kanji 「社会」mean?', '["reality/realize", "society", "improve", "improvement"]'::jsonb, 1, '社会 means ''society'' (on: シャ, kun: やしろ).', 'medium'),
(3, 17, 'kanji', 67, 'meaning', 'What does the kanji 「政治」mean?', '["politics", "environment", "maintain", "tendency"]'::jsonb, 0, '政治 means ''politics'' (on: セイ, kun: まつりごと).', 'medium'),
(3, 17, 'kanji', 68, 'meaning', 'What does the kanji 「文化」mean?', '["task/subject", "culture", "politics", "environment"]'::jsonb, 1, '文化 means ''culture'' (on: ブン, kun: ふみ).', 'medium'),
(3, 17, 'kanji', 69, 'meaning', 'What does the kanji 「契約」mean?', '["contract", "politics", "countermeasure", "environment"]'::jsonb, 0, '契約 means ''contract'' (on: ケイ, kun: ちぎ.る).', 'medium'),
(3, 17, 'kanji', 70, 'meaning', 'What does the kanji 「報告」mean?', '["countermeasure", "reality/realize", "influence", "report"]'::jsonb, 3, '報告 means ''report'' (on: ホウ, kun: むく.いる).', 'medium'),
(3, 17, 'kanji', 71, 'meaning', 'What does the kanji 「説明」mean?', '["explanation", "countermeasure", "culture", "contract"]'::jsonb, 0, '説明 means ''explanation'' (on: セツ, kun: と.く).', 'medium'),
(3, 17, 'kanji', 72, 'meaning', 'What does the kanji 「実現」mean?', '["politics", "reality/realize", "society", "countermeasure"]'::jsonb, 1, '実現 means ''reality/realize'' (on: ジツ, kun: み).', 'medium'),
(3, 17, 'kanji', 73, 'meaning', 'What does the kanji 「解決」mean?', '["solve/resolve", "countermeasure", "environment", "report"]'::jsonb, 0, '解決 means ''solve/resolve'' (on: カイ, kun: と.く).', 'medium'),
(3, 17, 'kanji', 74, 'meaning', 'What does the kanji 「向上」mean?', '["task/subject", "countermeasure", "improvement", "reality/realize"]'::jsonb, 2, '向上 means ''improvement'' (on: コウ, kun: む.く).', 'medium'),
(3, 17, 'kanji', 75, 'meaning', 'What does the kanji 「維持」mean?', '["maintain", "countermeasure", "solve/resolve", "environment"]'::jsonb, 0, '維持 means ''maintain'' (on: イ, kun: -).', 'medium'),
(3, 17, 'kanji', 76, 'meaning', 'What does the kanji 「改善」mean?', '["task/subject", "environment", "improve", "report"]'::jsonb, 2, '改善 means ''improve'' (on: カイ, kun: あらた.める).', 'medium'),
(4, 21, 'kanji', 77, 'meaning', 'What does the kanji 「概念」mean?', '["essence", "concept", "basis", "viewpoint"]'::jsonb, 1, '概念 means ''concept'' (on: ガイ, kun: おおむ.ね).', 'medium'),
(4, 21, 'kanji', 78, 'meaning', 'What does the kanji 「本質」mean?', '["perspective", "concept", "logic", "essence"]'::jsonb, 3, '本質 means ''essence'' (on: シツ, kun: たち).', 'medium'),
(4, 21, 'kanji', 79, 'meaning', 'What does the kanji 「論理」mean?', '["viewpoint", "inevitability", "logic", "element"]'::jsonb, 2, '論理 means ''logic'' (on: ロン, kun: -).', 'medium'),
(4, 21, 'kanji', 80, 'meaning', 'What does the kanji 「必然」mean?', '["speculation", "concern", "inevitability", "concept"]'::jsonb, 2, '必然 means ''inevitability'' (on: ヒツ, kun: かなら.ず).', 'medium'),
(4, 21, 'kanji', 81, 'meaning', 'What does the kanji 「要素」mean?', '["essence", "basis", "element", "speculation"]'::jsonb, 2, '要素 means ''element'' (on: ヨウ, kun: い.る).', 'medium'),
(4, 21, 'kanji', 82, 'meaning', 'What does the kanji 「背景」mean?', '["background", "perspective", "viewpoint", "concept"]'::jsonb, 0, '背景 means ''background'' (on: ハイ, kun: せ).', 'medium'),
(4, 21, 'kanji', 83, 'meaning', 'What does the kanji 「視点」mean?', '["viewpoint", "concept", "premise", "basis"]'::jsonb, 0, '視点 means ''viewpoint'' (on: シ, kun: み.る).', 'medium'),
(4, 21, 'kanji', 84, 'meaning', 'What does the kanji 「観点」mean?', '["logic", "perspective", "essence", "inevitability"]'::jsonb, 1, '観点 means ''perspective'' (on: カン, kun: み.る).', 'medium'),
(4, 21, 'kanji', 85, 'meaning', 'What does the kanji 「前提」mean?', '["basis", "concept", "premise", "element"]'::jsonb, 2, '前提 means ''premise'' (on: ゼン, kun: まえ).', 'medium'),
(4, 21, 'kanji', 86, 'meaning', 'What does the kanji 「根拠」mean?', '["element", "basis", "perspective", "concept"]'::jsonb, 1, '根拠 means ''basis'' (on: コン, kun: ね).', 'medium'),
(4, 21, 'kanji', 87, 'meaning', 'What does the kanji 「推測」mean?', '["concern", "speculation", "essence", "background"]'::jsonb, 1, '推測 means ''speculation'' (on: スイ, kun: お.す).', 'medium'),
(4, 21, 'kanji', 88, 'meaning', 'What does the kanji 「懸念」mean?', '["perspective", "concern", "essence", "basis"]'::jsonb, 1, '懸念 means ''concern'' (on: ケン, kun: か.ける).', 'medium');

INSERT INTO quiz_questions (level_id, module_id, source_type, source_id, question_type, question_text, options, correct_index, explanation, difficulty) VALUES
(5, 25, 'kanji', 89, 'meaning', 'What does the kanji 「矛盾」mean?', '["contradiction", "insight", "skepticism", "suggestion"]'::jsonb, 0, '矛盾 means ''contradiction'' (on: ム, kun: ほこ).', 'medium'),
(5, 25, 'kanji', 90, 'meaning', 'What does the kanji 「懐疑」mean?', '["harmful effect", "suggestion", "beginning/clue", "skepticism"]'::jsonb, 3, '懐疑 means ''skepticism'' (on: カイ, kun: ふところ).', 'medium'),
(5, 25, 'kanji', 91, 'meaning', 'What does the kanji 「洞察」mean?', '["universal", "insight", "suggestion", "beginning/clue"]'::jsonb, 1, '洞察 means ''insight'' (on: ドウ, kun: ほら).', 'medium'),
(5, 25, 'kanji', 92, 'meaning', 'What does the kanji 「逸脱」mean?', '["beginning/clue", "insight", "universal", "deviation"]'::jsonb, 3, '逸脱 means ''deviation'' (on: イツ, kun: そ.れる).', 'medium'),
(5, 25, 'kanji', 93, 'meaning', 'What does the kanji 「示唆」mean?', '["suggestion", "beginning/clue", "deviation", "harmful effect"]'::jsonb, 0, '示唆 means ''suggestion'' (on: シ, kun: しめ.す).', 'medium'),
(5, 25, 'kanji', 94, 'meaning', 'What does the kanji 「弊害」mean?', '["harmful effect", "suggestion", "insight", "skepticism"]'::jsonb, 0, '弊害 means ''harmful effect'' (on: ヘイ, kun: つい.える).', 'medium'),
(5, 25, 'kanji', 95, 'meaning', 'What does the kanji 「端緒」mean?', '["universal", "beginning/clue", "harmful effect", "contradiction"]'::jsonb, 1, '端緒 means ''beginning/clue'' (on: タン, kun: はし).', 'medium'),
(5, 25, 'kanji', 96, 'meaning', 'What does the kanji 「普遍」mean?', '["universal", "contradiction", "deviation", "insight"]'::jsonb, 0, '普遍 means ''universal'' (on: フ, kun: あまね.し).', 'medium'),
(1, 1, 'grammar', 1, 'meaning', 'What does the grammar pattern 「〜は〜です」express?', '["direction particle", "polite present aff/neg", "here/there/over-there/where", "N1 is N2"]'::jsonb, 3, '「〜は〜です」expresses: N1 is N2.', 'medium'),
(1, 1, 'grammar', 2, 'meaning', 'What does the grammar pattern 「〜じゃありません」express?', '["N is not (casual negative)", "question words", "also/too", "sequential actions"]'::jsonb, 0, '「〜じゃありません」expresses: N is not (casual negative).', 'medium'),
(1, 1, 'grammar', 3, 'meaning', 'What does the grammar pattern 「〜も」express?', '["not (い-adj)", "also/too", "polite past aff/neg", "comparison — than"]'::jsonb, 1, '「〜も」expresses: also/too.', 'medium'),
(1, 1, 'grammar', 4, 'meaning', 'What does the grammar pattern 「〜の〜」express?', '["like/dislike", "possessive", "this/that/that-over-there/which", "polite past aff/neg"]'::jsonb, 1, '「〜の〜」expresses: possessive.', 'medium'),
(1, 1, 'grammar', 5, 'meaning', 'What does the grammar pattern 「これ/それ/あれ/どれ」express?', '["this/that/that-over-there/which", "N is not (casual negative)", "direct object marker", "possessive"]'::jsonb, 0, '「これ/それ/あれ/どれ」expresses: this/that/that-over-there/which.', 'medium'),
(1, 1, 'grammar', 6, 'meaning', 'What does the grammar pattern 「ここ/そこ/あそこ/どこ」express?', '["here/there/over-there/where", "N is not (casual negative)", "possessive", "not (い-adj)"]'::jsonb, 0, '「ここ/そこ/あそこ/どこ」expresses: here/there/over-there/where.', 'medium'),
(1, 1, 'grammar', 7, 'meaning', 'What does the grammar pattern 「〜に あります/います」express?', '["attributive い-adj", "this/that/that-over-there/which", "attributive な-adj", "exists at (place)"]'::jsonb, 3, '「〜に あります/います」expresses: exists at (place).', 'medium'),
(1, 1, 'grammar', 8, 'meaning', 'What does the grammar pattern 「〜から〜まで」express?', '["from...to...", "question words", "direct object marker", "direction particle"]'::jsonb, 0, '「〜から〜まで」expresses: from...to....', 'medium'),
(1, 1, 'grammar', 9, 'meaning', 'What does the grammar pattern 「Vます/ません」express?', '["polite present aff/neg", "please do", "also/too", "attributive い-adj"]'::jsonb, 0, '「Vます/ません」expresses: polite present aff/neg.', 'medium'),
(1, 1, 'grammar', 10, 'meaning', 'What does the grammar pattern 「Vました/ませんでした」express?', '["not (な-adj)", "polite past aff/neg", "with (a person)", "exists at (place)"]'::jsonb, 1, '「Vました/ませんでした」expresses: polite past aff/neg.', 'medium'),
(1, 1, 'grammar', 11, 'meaning', 'What does the grammar pattern 「〜を」express?', '["want to (verb)", "direct object marker", "not (い-adj)", "past tense い-adj"]'::jsonb, 1, '「〜を」expresses: direct object marker.', 'medium'),
(1, 1, 'grammar', 12, 'meaning', 'What does the grammar pattern 「〜に いきます/きます/かえります」express?', '["direct object marker", "from...to...", "exists at (place)", "movement toward destination"]'::jsonb, 3, '「〜に いきます/きます/かえります」expresses: movement toward destination.', 'medium'),
(1, 1, 'grammar', 13, 'meaning', 'What does the grammar pattern 「〜で (means)」express?', '["N1 is N2", "here/there/over-there/where", "by/with (method)", "movement toward destination"]'::jsonb, 2, '「〜で (means)」expresses: by/with (method).', 'medium'),
(1, 1, 'grammar', 14, 'meaning', 'What does the grammar pattern 「〜と (companion)」express?', '["polite past aff/neg", "want to (verb)", "with (a person)", "polite present aff/neg"]'::jsonb, 2, '「〜と (companion)」expresses: with (a person).', 'medium'),
(1, 1, 'grammar', 15, 'meaning', 'What does the grammar pattern 「〜へ」express?', '["direction particle", "N1 is N2", "here/there/over-there/where", "ongoing action/state"]'::jsonb, 0, '「〜へ」expresses: direction particle.', 'medium'),
(1, 1, 'grammar', 16, 'meaning', 'What does the grammar pattern 「〜が ほしいです」express?', '["direction particle", "N is not (casual negative)", "comparison — than", "want (a thing)"]'::jsonb, 3, '「〜が ほしいです」expresses: want (a thing).', 'medium'),
(1, 1, 'grammar', 17, 'meaning', 'What does the grammar pattern 「Vたいです」express?', '["want to (verb)", "please do", "possessive", "ongoing action/state"]'::jsonb, 0, '「Vたいです」expresses: want to (verb).', 'medium'),
(1, 1, 'grammar', 18, 'meaning', 'What does the grammar pattern 「〜が すきです/きらいです」express?', '["direct object marker", "like/dislike", "with (a person)", "comparison — than"]'::jsonb, 1, '「〜が すきです/きらいです」expresses: like/dislike.', 'medium'),
(1, 1, 'grammar', 19, 'meaning', 'What does the grammar pattern 「い-adjective + Noun」express?', '["attributive い-adj", "past tense な-adj", "polite present aff/neg", "not (い-adj)"]'::jsonb, 0, '「い-adjective + Noun」expresses: attributive い-adj.', 'medium'),
(1, 1, 'grammar', 20, 'meaning', 'What does the grammar pattern 「な-adjective + Noun」express?', '["not (な-adj)", "polite present aff/neg", "attributive な-adj", "sequential actions"]'::jsonb, 2, '「な-adjective + Noun」expresses: attributive な-adj.', 'medium'),
(1, 1, 'grammar', 21, 'meaning', 'What does the grammar pattern 「い-adj negation くない」express?', '["not (い-adj)", "ongoing action/state", "with (a person)", "N1 is N2"]'::jsonb, 0, '「い-adj negation くない」expresses: not (い-adj).', 'medium'),
(1, 1, 'grammar', 22, 'meaning', 'What does the grammar pattern 「な-adj negation じゃありません」express?', '["this/that/that-over-there/which", "attributive い-adj", "not (な-adj)", "with (a person)"]'::jsonb, 2, '「な-adj negation じゃありません」expresses: not (な-adj).', 'medium'),
(1, 1, 'grammar', 23, 'meaning', 'What does the grammar pattern 「〜より」express?', '["by/with (method)", "direction particle", "past tense な-adj", "comparison — than"]'::jsonb, 3, '「〜より」expresses: comparison — than.', 'medium'),
(1, 1, 'grammar', 24, 'meaning', 'What does the grammar pattern 「〜の なかで〜いちばん」express?', '["polite past aff/neg", "movement toward destination", "by/with (method)", "superlative"]'::jsonb, 3, '「〜の なかで〜いちばん」expresses: superlative.', 'medium'),
(1, 1, 'grammar', 25, 'meaning', 'What does the grammar pattern 「て-form (request)」express?', '["N1 is N2", "superlative", "sequential actions", "please do"]'::jsonb, 3, '「て-form (request)」expresses: please do.', 'medium'),
(1, 1, 'grammar', 26, 'meaning', 'What does the grammar pattern 「〜ています」express?', '["ongoing action/state", "here/there/over-there/where", "polite past aff/neg", "like/dislike"]'::jsonb, 0, '「〜ています」expresses: ongoing action/state.', 'medium'),
(1, 1, 'grammar', 27, 'meaning', 'What does the grammar pattern 「V1て、V2」express?', '["sequential actions", "from...to...", "by/with (method)", "attributive い-adj"]'::jsonb, 0, '「V1て、V2」expresses: sequential actions.', 'medium'),
(1, 1, 'grammar', 28, 'meaning', 'What does the grammar pattern 「い-adj past かった」express?', '["past tense い-adj", "attributive な-adj", "sequential actions", "from...to..."]'::jsonb, 0, '「い-adj past かった」expresses: past tense い-adj.', 'medium'),
(1, 1, 'grammar', 29, 'meaning', 'What does the grammar pattern 「な-adj past でした」express?', '["question words", "N1 is N2", "past tense な-adj", "N is not (casual negative)"]'::jsonb, 2, '「な-adj past でした」expresses: past tense な-adj.', 'medium'),
(1, 1, 'grammar', 30, 'meaning', 'What does the grammar pattern 「疑問詞」express?', '["polite past aff/neg", "like/dislike", "question words", "please do"]'::jsonb, 2, '「疑問詞」expresses: question words.', 'medium'),
(2, 7, 'grammar', 31, 'meaning', 'What does the grammar pattern 「辞書形」express?', '["permission", "do in advance", "too much", "dictionary form"]'::jsonb, 3, '「辞書形」expresses: dictionary form.', 'medium'),
(2, 7, 'grammar', 32, 'meaning', 'What does the grammar pattern 「ない形」express?', '["plain negative", "automatic consequence", "plain past", "probability"]'::jsonb, 0, '「ない形」expresses: plain negative.', 'medium'),
(2, 7, 'grammar', 33, 'meaning', 'What does the grammar pattern 「た形」express?', '["permission", "plain past", "do in advance", "plain past negative"]'::jsonb, 1, '「た形」expresses: plain past.', 'medium'),
(2, 7, 'grammar', 34, 'meaning', 'What does the grammar pattern 「なかった形」express?', '["conditional on premise", "plain past negative", "automatic consequence", "permission"]'::jsonb, 1, '「なかった形」expresses: plain past negative.', 'medium'),
(2, 7, 'grammar', 35, 'meaning', 'What does the grammar pattern 「〜と思います」express?', '["conditional on premise", "must do", "I think that...", "passive form"]'::jsonb, 2, '「〜と思います」expresses: I think that....', 'medium'),
(2, 7, 'grammar', 36, 'meaning', 'What does the grammar pattern 「〜と言いました」express?', '["said that...", "automatic consequence", "potential form", "hypothetical conditional"]'::jsonb, 0, '「〜と言いました」expresses: said that....', 'medium'),
(2, 7, 'grammar', 37, 'meaning', 'What does the grammar pattern 「可能形」express?', '["permission", "said that...", "potential form", "plain past negative"]'::jsonb, 2, '「可能形」expresses: potential form.', 'medium'),
(2, 7, 'grammar', 38, 'meaning', 'What does the grammar pattern 「〜ができます」express?', '["permission", "can do N", "try doing", "give/receive"]'::jsonb, 1, '「〜ができます」expresses: can do N.', 'medium'),
(2, 7, 'grammar', 39, 'meaning', 'What does the grammar pattern 「意向形」express?', '["volitional — let''s do", "give/receive", "permission", "potential form"]'::jsonb, 0, '「意向形」expresses: volitional — let''s do.', 'medium'),
(2, 7, 'grammar', 40, 'meaning', 'What does the grammar pattern 「〜ようと思います」express?', '["I intend to...", "hearsay", "try doing", "automatic consequence"]'::jsonb, 0, '「〜ようと思います」expresses: I intend to....', 'medium'),
(2, 7, 'grammar', 41, 'meaning', 'What does the grammar pattern 「〜たら」express?', '["general conditional", "completion/regret", "I intend to...", "dictionary form"]'::jsonb, 0, '「〜たら」expresses: general conditional.', 'medium'),
(2, 7, 'grammar', 42, 'meaning', 'What does the grammar pattern 「〜ば」express?', '["hearsay", "dictionary form", "hypothetical conditional", "plain past negative"]'::jsonb, 2, '「〜ば」expresses: hypothetical conditional.', 'medium'),
(2, 7, 'grammar', 43, 'meaning', 'What does the grammar pattern 「〜と (natural result)」express?', '["easy/hard to do", "must do", "automatic consequence", "prohibition"]'::jsonb, 2, '「〜と (natural result)」expresses: automatic consequence.', 'medium'),
(2, 7, 'grammar', 44, 'meaning', 'What does the grammar pattern 「〜なら」express?', '["potential form", "give/receive", "conditional on premise", "hearsay"]'::jsonb, 2, '「〜なら」expresses: conditional on premise.', 'medium'),
(2, 7, 'grammar', 45, 'meaning', 'What does the grammar pattern 「あげる/もらう/くれる」express?', '["easy/hard to do", "plain past negative", "give/receive", "permission"]'::jsonb, 2, '「あげる/もらう/くれる」expresses: give/receive.', 'medium'),
(2, 7, 'grammar', 46, 'meaning', 'What does the grammar pattern 「受身形」express?', '["said that...", "permission", "must do", "passive form"]'::jsonb, 3, '「受身形」expresses: passive form.', 'medium'),
(2, 7, 'grammar', 47, 'meaning', 'What does the grammar pattern 「〜なければなりません」express?', '["try doing", "must do", "plain negative", "dictionary form"]'::jsonb, 1, '「〜なければなりません」expresses: must do.', 'medium'),
(2, 7, 'grammar', 48, 'meaning', 'What does the grammar pattern 「〜てもいいです」express?', '["said that...", "permission", "volitional — let''s do", "hypothetical conditional"]'::jsonb, 1, '「〜てもいいです」expresses: permission.', 'medium'),
(2, 7, 'grammar', 49, 'meaning', 'What does the grammar pattern 「〜てはいけません」express?', '["hearsay", "hypothetical conditional", "prohibition", "plain past"]'::jsonb, 2, '「〜てはいけません」expresses: prohibition.', 'medium'),
(2, 7, 'grammar', 50, 'meaning', 'What does the grammar pattern 「〜そうです (伝聞)」express?', '["plain negative", "dictionary form", "can do N", "hearsay"]'::jsonb, 3, '「〜そうです (伝聞)」expresses: hearsay.', 'medium'),
(2, 7, 'grammar', 51, 'meaning', 'What does the grammar pattern 「〜でしょう」express?', '["probability", "hearsay", "give/receive", "plain negative"]'::jsonb, 0, '「〜でしょう」expresses: probability.', 'medium'),
(2, 7, 'grammar', 52, 'meaning', 'What does the grammar pattern 「〜てみる」express?', '["prohibition", "plain negative", "try doing", "said that..."]'::jsonb, 2, '「〜てみる」expresses: try doing.', 'medium'),
(2, 7, 'grammar', 53, 'meaning', 'What does the grammar pattern 「〜ておく」express?', '["do in advance", "give/receive", "I intend to...", "conditional on premise"]'::jsonb, 0, '「〜ておく」expresses: do in advance.', 'medium'),
(2, 7, 'grammar', 54, 'meaning', 'What does the grammar pattern 「〜てしまう」express?', '["can do N", "automatic consequence", "completion/regret", "try doing"]'::jsonb, 2, '「〜てしまう」expresses: completion/regret.', 'medium'),
(2, 7, 'grammar', 55, 'meaning', 'What does the grammar pattern 「〜すぎる」express?', '["do in advance", "passive form", "too much", "automatic consequence"]'::jsonb, 2, '「〜すぎる」expresses: too much.', 'medium'),
(2, 7, 'grammar', 56, 'meaning', 'What does the grammar pattern 「〜やすい/にくい」express?', '["automatic consequence", "easy/hard to do", "said that...", "hypothetical conditional"]'::jsonb, 1, '「〜やすい/にくい」expresses: easy/hard to do.', 'medium'),
(3, 13, 'grammar', 57, 'meaning', 'What does the grammar pattern 「〜ため(に)」express?', '["purpose/cause", "causative", "because of (negative)", "causative-passive"]'::jsonb, 0, '「〜ため(に)」expresses: purpose/cause.', 'medium'),
(3, 13, 'grammar', 58, 'meaning', 'What does the grammar pattern 「〜のに」express?', '["despite/although", "doing two things at once", "causative-passive", "must be"]'::jsonb, 0, '「〜のに」expresses: despite/although.', 'medium'),
(3, 13, 'grammar', 59, 'meaning', 'What does the grammar pattern 「〜わりに」express?', '["because of (negative)", "causative-passive", "considering", "irregular humble verbs"]'::jsonb, 2, '「〜わりに」expresses: considering.', 'medium'),
(3, 13, 'grammar', 60, 'meaning', 'What does the grammar pattern 「〜ながら」express?', '["it has been decided", "doing two things at once", "irregular humble verbs", "causative"]'::jsonb, 1, '「〜ながら」expresses: doing two things at once.', 'medium'),
(3, 13, 'grammar', 61, 'meaning', 'What does the grammar pattern 「〜あいだ(に)」express?', '["while/during", "irregular humble verbs", "must be", "respectful form"]'::jsonb, 0, '「〜あいだ(に)」expresses: while/during.', 'medium'),
(3, 13, 'grammar', 62, 'meaning', 'What does the grammar pattern 「尊敬語 お〜になる」express?', '["while/during", "should be", "because of (negative)", "respectful form"]'::jsonb, 3, '「尊敬語 お〜になる」expresses: respectful form.', 'medium'),
(3, 13, 'grammar', 63, 'meaning', 'What does the grammar pattern 「謙譲語 お〜する」express?', '["respectful form", "humble form", "because of (negative)", "causative"]'::jsonb, 1, '「謙譲語 お〜する」expresses: humble form.', 'medium'),
(3, 13, 'grammar', 64, 'meaning', 'What does the grammar pattern 「特別な尊敬語」express?', '["humble form", "causative-passive", "might/may", "irregular respectful verbs"]'::jsonb, 3, '「特別な尊敬語」expresses: irregular respectful verbs.', 'medium'),
(3, 13, 'grammar', 65, 'meaning', 'What does the grammar pattern 「特別な謙譲語」express?', '["irregular respectful verbs", "decide to", "irregular humble verbs", "while/during"]'::jsonb, 2, '「特別な謙譲語」expresses: irregular humble verbs.', 'medium'),
(3, 13, 'grammar', 66, 'meaning', 'What does the grammar pattern 「〜はずです」express?', '["causative", "so that", "irregular respectful verbs", "should be"]'::jsonb, 3, '「〜はずです」expresses: should be.', 'medium'),
(3, 13, 'grammar', 67, 'meaning', 'What does the grammar pattern 「〜かもしれません」express?', '["might/may", "doing two things at once", "thanks to", "while/during"]'::jsonb, 0, '「〜かもしれません」expresses: might/may.', 'medium'),
(3, 13, 'grammar', 68, 'meaning', 'What does the grammar pattern 「〜にちがいない」express?', '["must be", "purpose/cause", "causative-passive", "while/during"]'::jsonb, 0, '「〜にちがいない」expresses: must be.', 'medium'),
(3, 13, 'grammar', 69, 'meaning', 'What does the grammar pattern 「使役形」express?', '["respectful form", "causative", "considering", "irregular respectful verbs"]'::jsonb, 1, '「使役形」expresses: causative.', 'medium'),
(3, 13, 'grammar', 70, 'meaning', 'What does the grammar pattern 「使役受身形」express?', '["because of (negative)", "causative-passive", "considering", "must be"]'::jsonb, 1, '「使役受身形」expresses: causative-passive.', 'medium'),
(3, 13, 'grammar', 71, 'meaning', 'What does the grammar pattern 「〜ことになる」express?', '["it has been decided", "considering", "should be", "irregular respectful verbs"]'::jsonb, 0, '「〜ことになる」expresses: it has been decided.', 'medium'),
(3, 13, 'grammar', 72, 'meaning', 'What does the grammar pattern 「〜ことにする」express?', '["must be", "should be", "causative", "decide to"]'::jsonb, 3, '「〜ことにする」expresses: decide to.', 'medium'),
(3, 13, 'grammar', 73, 'meaning', 'What does the grammar pattern 「〜ば〜ほど」express?', '["irregular humble verbs", "respectful form", "the more...the more", "purpose/cause"]'::jsonb, 2, '「〜ば〜ほど」expresses: the more...the more.', 'medium'),
(3, 13, 'grammar', 74, 'meaning', 'What does the grammar pattern 「〜おかげで」express?', '["causative-passive", "it has been decided", "thanks to", "purpose/cause"]'::jsonb, 2, '「〜おかげで」expresses: thanks to.', 'medium'),
(3, 13, 'grammar', 75, 'meaning', 'What does the grammar pattern 「〜せいで」express?', '["should be", "because of (negative)", "respectful form", "doing two things at once"]'::jsonb, 1, '「〜せいで」expresses: because of (negative).', 'medium'),
(3, 13, 'grammar', 76, 'meaning', 'What does the grammar pattern 「〜ように」express?', '["because of (negative)", "despite/although", "so that", "causative"]'::jsonb, 2, '「〜ように」expresses: so that.', 'medium'),
(4, 18, 'grammar', 77, 'meaning', 'What does the grammar pattern 「〜にもかかわらず」express?', '["as long as", "only/ever since", "after all that", "despite"]'::jsonb, 3, '「〜にもかかわらず」expresses: despite.', 'medium'),
(4, 18, 'grammar', 78, 'meaning', 'What does the grammar pattern 「〜ものの」express?', '["although", "cushioning phrase", "not until after", "as long as"]'::jsonb, 0, '「〜ものの」expresses: although.', 'medium'),
(4, 18, 'grammar', 79, 'meaning', 'What does the grammar pattern 「〜ばかりに」express?', '["unless", "just because of", "allow me to", "can''t help but"]'::jsonb, 1, '「〜ばかりに」expresses: just because of.', 'medium'),
(4, 18, 'grammar', 80, 'meaning', 'What does the grammar pattern 「〜あげく」express?', '["although", "after all that", "despite", "not until after"]'::jsonb, 1, '「〜あげく」expresses: after all that.', 'medium'),
(4, 18, 'grammar', 81, 'meaning', 'What does the grammar pattern 「〜うえで」express?', '["although", "in the process of", "not until after", "after all that"]'::jsonb, 1, '「〜うえで」expresses: in the process of.', 'medium'),
(4, 18, 'grammar', 82, 'meaning', 'What does the grammar pattern 「〜かぎり」express?', '["as long as", "can''t help but", "it''s not that...", "only/ever since"]'::jsonb, 0, '「〜かぎり」expresses: as long as.', 'medium'),
(4, 18, 'grammar', 83, 'meaning', 'What does the grammar pattern 「〜わけではない」express?', '["unless", "can''t help but", "it''s not that...", "after all that"]'::jsonb, 2, '「〜わけではない」expresses: it''s not that....', 'medium'),
(4, 18, 'grammar', 84, 'meaning', 'What does the grammar pattern 「〜どころか」express?', '["as long as", "it''s not that...", "far from", "allow me to"]'::jsonb, 2, '「〜どころか」expresses: far from.', 'medium'),
(4, 18, 'grammar', 85, 'meaning', 'What does the grammar pattern 「〜させていただきます」express?', '["not until after", "cushioning phrase", "allow me to", "despite"]'::jsonb, 2, '「〜させていただきます」expresses: allow me to.', 'medium'),
(4, 18, 'grammar', 86, 'meaning', 'What does the grammar pattern 「恐れ入りますが」express?', '["cushioning phrase", "only/ever since", "after all that", "far from"]'::jsonb, 0, '「恐れ入りますが」expresses: cushioning phrase.', 'medium'),
(4, 18, 'grammar', 87, 'meaning', 'What does the grammar pattern 「〜ないことには」express?', '["just because of", "unless", "in process of", "allow me to"]'::jsonb, 1, '「〜ないことには」expresses: unless.', 'medium'),
(4, 18, 'grammar', 88, 'meaning', 'What does the grammar pattern 「〜てからでないと」express?', '["after all that", "not until after", "despite", "just because of"]'::jsonb, 1, '「〜てからでないと」expresses: not until after.', 'medium'),
(4, 18, 'grammar', 89, 'meaning', 'What does the grammar pattern 「〜ずにはいられない」express?', '["after all that", "can''t help but", "although", "unless"]'::jsonb, 1, '「〜ずにはいられない」expresses: can''t help but.', 'medium'),
(4, 18, 'grammar', 90, 'meaning', 'What does the grammar pattern 「〜きり」express?', '["not until after", "far from", "unless", "only/ever since"]'::jsonb, 3, '「〜きり」expresses: only/ever since.', 'medium'),
(4, 18, 'grammar', 91, 'meaning', 'What does the grammar pattern 「〜つつある」express?', '["not until after", "allow me to", "despite", "in process of"]'::jsonb, 3, '「〜つつある」expresses: in process of.', 'medium'),
(5, 22, 'grammar', 92, 'meaning', 'What does the grammar pattern 「〜べからず」express?', '["must not (classical)", "as if about to", "regardless of", "no sooner than"]'::jsonb, 0, '「〜べからず」expresses: must not (classical).', 'medium'),
(5, 22, 'grammar', 93, 'meaning', 'What does the grammar pattern 「〜なくして(は)」express?', '["unique to", "by means of", "without doing", "without"]'::jsonb, 3, '「〜なくして(は)」expresses: without.', 'medium'),
(5, 22, 'grammar', 94, 'meaning', 'What does the grammar pattern 「〜をもって」express?', '["even if not", "by means of", "cannot help but feel", "tends to"]'::jsonb, 1, '「〜をもって」expresses: by means of.', 'medium'),
(5, 22, 'grammar', 95, 'meaning', 'What does the grammar pattern 「〜いかんによらず」express?', '["regardless of", "tends to", "must not (classical)", "without doing"]'::jsonb, 0, '「〜いかんによらず」expresses: regardless of.', 'medium'),
(5, 22, 'grammar', 96, 'meaning', 'What does the grammar pattern 「〜や否や」express?', '["the moment", "extremely", "regardless of", "no sooner than"]'::jsonb, 0, '「〜や否や」expresses: the moment.', 'medium'),
(5, 22, 'grammar', 97, 'meaning', 'What does the grammar pattern 「〜そばから」express?', '["tends to", "no sooner than", "without", "by means of"]'::jsonb, 1, '「〜そばから」expresses: no sooner than.', 'medium'),
(5, 22, 'grammar', 98, 'meaning', 'What does the grammar pattern 「〜なしに」express?', '["without doing", "cannot help but feel", "the moment", "no sooner than"]'::jsonb, 0, '「〜なしに」expresses: without doing.', 'medium'),
(5, 22, 'grammar', 99, 'meaning', 'What does the grammar pattern 「〜ないまでも」express?', '["tends to", "extremely", "must not (classical)", "even if not"]'::jsonb, 3, '「〜ないまでも」expresses: even if not.', 'medium'),
(5, 22, 'grammar', 100, 'meaning', 'What does the grammar pattern 「〜きらいがある」express?', '["tends to", "cannot help but feel", "the moment", "as if about to"]'::jsonb, 0, '「〜きらいがある」expresses: tends to.', 'medium'),
(5, 22, 'grammar', 101, 'meaning', 'What does the grammar pattern 「〜にたえない」express?', '["cannot bear to", "even if not", "without doing", "regardless of"]'::jsonb, 0, '「〜にたえない」expresses: cannot bear to.', 'medium'),
(5, 22, 'grammar', 102, 'meaning', 'What does the grammar pattern 「〜を禁じ得ない」express?', '["unique to", "without", "cannot help but feel", "the moment"]'::jsonb, 2, '「〜を禁じ得ない」expresses: cannot help but feel.', 'medium'),
(5, 22, 'grammar', 103, 'meaning', 'What does the grammar pattern 「〜ならでは」express?', '["as if about to", "by means of", "unique to", "without"]'::jsonb, 2, '「〜ならでは」expresses: unique to.', 'medium'),
(5, 22, 'grammar', 104, 'meaning', 'What does the grammar pattern 「〜んばかりに」express?', '["by means of", "as if about to", "extremely", "the moment"]'::jsonb, 1, '「〜んばかりに」expresses: as if about to.', 'medium'),
(5, 22, 'grammar', 105, 'meaning', 'What does the grammar pattern 「〜てやまない」express?', '["without", "as if about to", "never ceasing to", "unique to"]'::jsonb, 2, '「〜てやまない」expresses: never ceasing to.', 'medium'),
(5, 22, 'grammar', 106, 'meaning', 'What does the grammar pattern 「〜極まりない」express?', '["extremely", "without doing", "by means of", "cannot help but feel"]'::jsonb, 0, '「〜極まりない」expresses: extremely.', 'medium');
